# -*- coding: utf-8 -*-
"""cycle_1_signals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AmHjD3K6IkP-sy8TuagyKV_rx6bVWrl3
"""

import pandas as pd
import numpy as np
from pandas.tseries.holiday import USFederalHolidayCalendar
import os
from google.colab import drive

# ------------------------------------------------------------------------------
# 1. DATA LOADING
# ------------------------------------------------------------------------------
def load_data():
    if not os.path.exists("/content/drive/My Drive"):
        drive.mount("/content/drive")

    base_path = "/content/drive/My Drive/Prometheus/First cycle/"
    gld_path = os.path.join(base_path, "GLD_Train_val.csv")

    if not os.path.exists(gld_path):
        raise FileNotFoundError(f"Could not find the main GLD file at {gld_path}.")

    df = pd.read_csv(gld_path, index_col="Date", parse_dates=True)
    df = df[~df.index.duplicated(keep="first")].sort_index()

    macro_files = {
        "GDX_Train_val.csv":       "GDX",
        "df_EURUSD_Train_val.csv": "EUR",
        "df_VIX_Train_val.csv":    "VIX",
        "df_SPX_Train_val.csv":    "SPX",
        "df_NDX_Train_val.csv":    "NDX",
        "df_US10Y_Train_val.csv":  "US10Y",
        "df_US2Y_Train_val.csv":   "US2Y",
        "Copper_Train_test.csv":   "Copper",
        "df_VVIX_Train_val.csv":   "VVIX",
        "USDJPY_Train_test.csv":   "UJ"}

    for filename, suffix in macro_files.items():
        file_path = os.path.join(base_path, filename)
        if os.path.exists(file_path):
            macro_df = pd.read_csv(file_path, index_col="Date", parse_dates=True)
            macro_df = macro_df[~macro_df.index.duplicated(keep="first")].sort_index()

            if suffix == "VIX":
                cols = [c for c in["Open", "High", "Low", "Close"] if c in macro_df.columns]
                macro_data = macro_df[cols].rename(columns={c: f"{c}_VIX" for c in cols})
            else:
                macro_data = macro_df[["Close"]].rename(columns={"Close": f"Close_{suffix}"})

            df = df.join(macro_data, how="left")
        else:
            print(f"Warning: Could not find {filename} at {base_path}")

    df = df.ffill()
    core_cols = ["Open", "High", "Low", "Close", "Volume"]
    df = df.dropna(subset=core_cols)

    return df

# ------------------------------------------------------------------------------
# 2. SHARED UTILITIES
# ------------------------------------------------------------------------------
def compute_base(df):
    c = df["Close"]
    h = df["High"]
    l = df["Low"]
    v = df["Volume"]
    o = df["Open"]

    ret = c.pct_change()
    tr = np.maximum(h - l, np.maximum((h - c.shift(1)).abs(), (l - c.shift(1)).abs()))

    vol20 = ret.rolling(20).std() * np.sqrt(252)
    vol60 = ret.rolling(60).std() * np.sqrt(252)
    vol_adj = (0.15 / (vol20 + 1e-8)).replace([np.inf, -np.inf], np.nan).fillna(1).clip(0.5, 2.0)

    return o, h, l, c, v, ret, tr, vol20, vol60, vol_adj

def calc_rsi(series, period):
    delta = series.diff()
    gain = delta.where(delta > 0, 0).rolling(period).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(period).mean()
    rs = gain / (loss + 1e-8)
    return 100 - (100 / (1 + rs))

def calc_chop(h, l, c, period):
    tr = np.maximum(h - l, np.maximum((h - c.shift(1)).abs(), (l - c.shift(1)).abs()))
    sum_tr = tr.rolling(period).sum()
    highest = h.rolling(period).max()
    lowest = l.rolling(period).min()
    return 100 * np.log10(sum_tr / (highest - lowest + 1e-8)) / np.log10(period)

def calc_er(c, period):
    change = c.diff(period).abs()
    volatility = c.diff().abs().rolling(period).sum()
    return change / (volatility + 1e-8)

def zscore(series, period):
    return (series - series.rolling(period).mean()) / (series.rolling(period).std() + 1e-8)

def tanh_clip(series, scale=1.0):
    return np.tanh(series / scale)

# ------------------------------------------------------------------------------
# 3. SEASONALITY SIGNALS
# ------------------------------------------------------------------------------
def build_seasonal_signals(df):
    o, h, l, c, v, ret, tr, vol20, vol60, vol_adj = compute_base(df)

    month = df.index.month
    t_to_eom = df.groupby([df.index.year, df.index.month]).cumcount(ascending=False)
    t_from_bom = df.groupby([df.index.year, df.index.month]).cumcount(ascending=True)

    cal = USFederalHolidayCalendar()
    holidays = cal.holidays(start=df.index.min(), end=df.index.max())
    is_pre_hol = pd.Series([
        1 if (d + pd.Timedelta(days=1) in holidays or
              d + pd.Timedelta(days=2) in holidays or
             (d + pd.Timedelta(days=3) in holidays and d.dayofweek == 4)) else 0
        for d in df.index], index=df.index)

    sma50 = c.rolling(50).mean()
    sma100 = c.rolling(100).mean()
    clv = ((c - l) - (h - c)) / (h - l + 1e-8)
    bb_width = (c.rolling(20).std() * 4) / c.rolling(20).mean()
    er10 = calc_er(c, 10)

    b_tom = np.where((t_to_eom <= 3) | (t_from_bom <= 3), 1, 0)
    sig_1 = pd.Series(b_tom, index=c.index).shift(1) * (vol20 >= vol60).astype(int)

    b_jan = np.where((month == 1) & (c < sma50), 1, 0)
    sig_2 = b_jan * (clv > 0).astype(int)

    b_dec = np.where((month == 12) & (t_to_eom <= 10), 1, 0)
    sig_3 = pd.Series(b_dec, index=c.index).shift(1) * (vol20 < vol60).astype(int)

    b_rob = np.where(np.isin(month,[7, 11, 12]), 1, np.where(month == 6, -1, 0))
    sig_4 = b_rob * (bb_width < bb_width.rolling(252).median()).astype(int) * (er10 <= 0.5).astype(int)

    sig_5 = is_pre_hol * (c > sma100).astype(int)

    return {
        "Sea_01_TOM_VolExp":      pd.Series(sig_1, index=c.index).shift(1).fillna(0),
        "Sea_02_Jan_MeanRev":     pd.Series(sig_2, index=c.index).shift(1).fillna(0),
        "Sea_03_Dec_VolContr":    pd.Series(sig_3, index=c.index).shift(1).fillna(0),
        "Sea_04_RobustM_BBSqz":   pd.Series(sig_4, index=c.index).shift(1).fillna(0),
        "Sea_05_PreHol_Trend100": pd.Series(sig_5, index=c.index).shift(1).fillna(0)}

# ------------------------------------------------------------------------------
# 4. VOLUME SIGNALS
# ------------------------------------------------------------------------------
def build_volume_signals(df):
    o, h, l, c, v, ret, tr, vol20, vol60, vol_adj = compute_base(df)

    chop14 = calc_chop(h, l, c, 14)
    rsi14 = calc_rsi(c, 14)
    roll_max14 = c.rolling(14).max()
    ulcer = np.sqrt((((c - roll_max14) / roll_max14 * 100)**2).rolling(14).mean())
    gap = (o / c.shift(1) - 1).abs()

    b1 = tanh_clip(v.pct_change(5) * np.sign(ret))
    v_climax = v > v.rolling(252).quantile(0.95)
    sig_1 = np.where(v_climax, -b1, b1) * (chop14 < 50)

    v_scale = v / v.rolling(50).mean()
    b2 = tanh_clip(zscore(ret, 20) * (v / v.rolling(20).mean() - 1.25))
    sig_2 = np.clip(b2 * v_scale, -1, 1) / (ulcer + 1)

    b3 = tanh_clip(zscore(c, 10)) * np.clip(zscore(v, 10), 0, 1)
    sig_3 = b3 * (c < c.rolling(50).mean()) * (gap < 0.005)

    b4 = tanh_clip(zscore(v, 10) * np.sign(ret))
    s4_temp = np.where(b4 > 0, b4, b4 * 0.5)
    sig_4 = np.where((rsi14 > 80) & (s4_temp > 0), -s4_temp, np.where((rsi14 < 20) & (s4_temp < 0), -s4_temp, s4_temp))

    mfm = ((c - l) - (h - c)) / (h - l + 1e-8)
    cmf10 = (mfm * v).rolling(10).sum() / (v.rolling(10).sum() + 1e-8)
    s5_temp = cmf10 * np.sign(v - v.shift(1))
    sig_5 = np.where(s5_temp < 0, s5_temp * 0.25, s5_temp)

    return {
        "Vol_01_VROC_ClimaxFade": pd.Series(sig_1, index=c.index).shift(1).fillna(0),
        "Vol_02_ZThresh_Scale":   pd.Series(sig_2, index=c.index).shift(1).fillna(0),
        "Vol_03_PVTrend_Gap":     pd.Series(sig_3, index=c.index).shift(1).fillna(0),
        "Vol_04_ZMom_ExtremeRSI": pd.Series(sig_4, index=c.index).shift(1).fillna(0),
        "Vol_05_CMF_Accel":       pd.Series(sig_5, index=c.index).shift(1).fillna(0)}

# ------------------------------------------------------------------------------
# 5. BREADTH SIGNALS
# ------------------------------------------------------------------------------
def build_breadth_base_signals(df):
    o, h, l, c, v, ret, tr, vol20, vol60, vol_adj = compute_base(df)

    up = (ret > 0).astype(int)
    upvol = up * v
    intra_up = (c > o).astype(int)
    dow = df.index.dayofweek
    rsi14 = calc_rsi(c, 14)

    ibm_raw = np.tanh((intra_up.rolling(3).mean() - intra_up.rolling(15).mean()) * 10)
    sig_1 = np.where(c < c.rolling(5).max() * 0.98, 0, np.where(ibm_raw > 0, ibm_raw, 0))

    ud10 = up.rolling(10).mean()
    sig_2 = ((ud10.rolling(10).min() <= 0.2) & (ud10 >= 0.8)).astype(int).shift(1).replace(0, np.nan).ffill(limit=10).fillna(0)

    mas = [c.rolling(w).mean() for w in[5, 10, 20, 50, 100, 200]]
    ma_align = sum((c > ma).astype(int) for ma in mas) / 6.0
    maam_raw = np.tanh((ma_align.rolling(3).mean() - ma_align.rolling(20).mean()) * 10)
    maam_long = np.where(maam_raw > 0, maam_raw, 0)
    sig_3 = np.where(dow == 4, -maam_long, maam_long)

    vol_ud20 = upvol.rolling(20).sum() / (v.rolling(20).sum() + 1e-8)
    z_vwudr = (vol_ud20 - vol_ud20.rolling(252).mean()) / (vol_ud20.rolling(252).std() + 1e-8)
    vwudr_raw = -np.tanh(z_vwudr)
    vol_regime = vol20 / (ret.rolling(100).std() * np.sqrt(252) + 1e-8)
    sig_4 = np.where(vol_regime > 1.2, np.where(vwudr_raw > 0, vwudr_raw, 0), 0)

    stbr_raw = -(up.rolling(2).mean() - 0.5) * 2
    sig_5 = np.where((dow == 4) | (rsi14 > 80) | (rsi14 < 20), 0, stbr_raw)

    return {
        "BrB_01_Intraday_Mom":   pd.Series(sig_1, index=c.index).shift(1).fillna(0),
        "BrB_02_Thrust_BTI":     pd.Series(sig_2, index=c.index).shift(1).fillna(0),
        "BrB_03_MA_Align_Mom":   pd.Series(sig_3, index=c.index).shift(1).fillna(0),
        "BrB_04_VolWeight_Rev":  pd.Series(sig_4, index=c.index).shift(1).fillna(0),
        "BrB_05_ShortTerm_Rev":  pd.Series(sig_5, index=c.index).shift(1).fillna(0)}

# ------------------------------------------------------------------------------
# 6. MACRO BREADTH SIGNALS
# ------------------------------------------------------------------------------
def build_macro_breadth_signals(df):
    if "Close_GDX" not in df.columns: return {}
    o, h, l, c, v, ret, tr, vol20, vol60, vol_adj = compute_base(df)

    r_gdx = df["Close_GDX"].pct_change()
    r_eur = df["Close_EUR"].pct_change()
    r_vix = df["Close_VIX"].pct_change()
    r_spx = df["Close_SPX"].pct_change()
    r_ndx = df["Close_NDX"].pct_change()
    r_u10 = df["Close_US10Y"].pct_change()
    r2_cu = df["Close_Copper"].pct_change(2)
    r2_u2 = df["Close_US2Y"].pct_change(2)
    r2_vv = df["Close_VVIX"].pct_change(2)

    base_sig_10 = (zscore(df["Close_GDX"]/c, 10) / 3).clip(-1, 1)
    eur_trend = (df["Close_EUR"] > df["Close_EUR"].rolling(20).mean()).astype(int)
    comp_ret = r_gdx + r_eur - r_vix
    vol_exp = (vol20 > ret.rolling(100).std() * np.sqrt(252)).astype(int)
    panic = ((r_gdx < -0.01) & (r_eur < -0.005) & (r_vix > 0.05)).astype(int).rolling(10).max().fillna(0)

    # Group GDX, VIX & EUR/USD
    sig_1 = np.sign((base_sig_10 + 0.5 * eur_trend).clip(-1, 1)) * (ret < 0.01) * (r_gdx.rolling(10).sum() > 0)

    sig_2 = np.where(((base_sig_10 + panic).clip(-1, 1) * vol_exp < 0) & (df["Close_VIX"] > 20), 0, (base_sig_10 + panic).clip(-1, 1) * vol_exp)

    s3_raw = (zscore(comp_ret, 50) / 3).clip(-1, 1) * (vol20 > vol20.rolling(50).mean()) * (ret.rolling(50).skew() < 0)
    sig_3 = np.where((s3_raw > 0) & (df["Close_VIX"] > 25), s3_raw * 2, s3_raw).clip(-1, 1)

    sig_4_temp = ((comp_ret > 0).rolling(20).sum() - 10) / 5
    sig_4 = (sig_4_temp + panic).clip(-1, 1) * vol_exp * ((ret > 0).rolling(3).sum() <= 1)

    sig_5 = np.where(df["Close_EUR"] < df["Close_EUR"].rolling(50).mean(), panic * (ret.rolling(50).corr(r_gdx) > 0.85) * 0.5, panic * (ret.rolling(50).corr(r_gdx) > 0.85))

    # Group SPX, NDX & US10Y
    adl = (np.sign(r_spx) + np.sign(r_ndx) + np.sign(r_u10)).cumsum()
    sig_6 = np.maximum(0, (adl > adl.rolling(20).mean()).astype(int) * 2 - 1)

    spx_bear = df["Close_SPX"] < df["Close_SPX"].rolling(200).mean()
    s7_base = (r_spx.rolling(20).corr(r_u10) > 0).astype(int) * 2 - 1
    sig_7 = np.where(s7_base < 0, np.where(spx_bear, s7_base, 0), s7_base)

    sig_8 = ((df["Close_NDX"]/df["Close_SPX"]).pct_change(200) > 0) & (df["Close_US10Y"].pct_change(200) < 0)
    sig_8 = sig_8 * ((df["Close_NDX"]/df["Close_SPX"]).pct_change(20) > 0)

    s9_base = (np.sign(r_spx) + np.sign(r_ndx) + np.sign(r_u10)).rolling(20).mean() / 3.0
    sig_9 = np.where(s9_base < 0, np.where(spx_bear, s9_base, 0), s9_base)

    adv = (r_spx > 0).astype(int) + (r_ndx > 0).astype(int) + (r_u10 > 0).astype(int) + (ret > 0).astype(int)
    s10_base = (adv / 4.0).rolling(20).mean() * 2 - 1
    ribbon = (c.rolling(10).mean() > c.rolling(20).mean()) & (c.rolling(20).mean() > c.rolling(50).mean())
    sig_10 = s10_base * ribbon

    # Group VVIX, COPPER & US2Y
    vv_norm = df["Close_VVIX"] / df["Close_VVIX"].rolling(252).mean()
    s11_base = np.where((np.sign(r2_cu) == -1) & (np.sign(r2_u2) == -1), 1, np.where((np.sign(r2_cu) == 1) & (np.sign(r2_u2) == 1) & (np.sign(r2_vv) == 1), -1, 0))
    sig_11 = np.where(s11_base > 0, s11_base * vv_norm, 0)

    cu_u2 = df["Close_Copper"] / df["Close_US2Y"]
    sig_12 = np.where(c > c.rolling(200).mean(), np.sign(cu_u2 - cu_u2.rolling(100).mean()), 0)

    br_c = (df["Close_Copper"] > df["Close_Copper"].rolling(50).mean()).astype(int) + (df["Close_US2Y"] < df["Close_US2Y"].rolling(50).mean()).astype(int) + (df["Close_VVIX"] < df["Close_VVIX"].rolling(50).mean()).astype(int)
    sig_13 = np.where((df.index.dayofweek != 4) & (br_c >= 1) & (c > c.rolling(50).mean()), 1, 0)

    rr_10 = zscore(df["Close_US2Y"], 10) - zscore(df["Close_Copper"], 10)
    s14_temp = pd.Series(np.where(rr_10 < rr_10.rolling(10).mean(), 1, -1)).ewm(span=3).mean()
    sig_14 = np.where(df.index.dayofweek == 4, 0, np.where(s14_temp > 0, s14_temp, 0))

    rr_50 = zscore(df["Close_US2Y"], 50) - zscore(df["Close_Copper"], 50)
    s15_temp = pd.Series(np.where(rr_50 < rr_50.rolling(50).mean(), 1, -1)).rolling(5).mean()
    sig_15 = np.where(s15_temp > 0, s15_temp, 0) * (df["Close_US2Y"] / df["Close_US2Y"].rolling(200).mean())

    return {
        "Mac_01_GDX_TrendMiner": pd.Series(sig_1, index=c.index).shift(1).fillna(0),
        "Mac_02_Ratio_Panic":    pd.Series(sig_2, index=c.index).shift(1).fillna(0),
        "Mac_03_CompBreadth":    pd.Series(sig_3, index=c.index).shift(1).fillna(0),
        "Mac_04_EcoDays":        pd.Series(sig_4, index=c.index).shift(1).fillna(0),
        "Mac_05_PurePanic":      pd.Series(sig_5, index=c.index).shift(1).fillna(0),
        "Mac_06_ADL_LongOnly":   pd.Series(sig_6, index=c.index).shift(1).fillna(0),
        "Mac_07_Corr_SPXBear":   pd.Series(sig_7, index=c.index).shift(1).fillna(0),
        "Mac_08_TechOutperf":    pd.Series(sig_8, index=c.index).shift(1).fillna(0),
        "Mac_09_SmBreadthBear":  pd.Series(sig_9, index=c.index).shift(1).fillna(0),
        "Mac_10_PropAdv_Ribbon": pd.Series(sig_10, index=c.index).shift(1).fillna(0),
        "Mac_11_W2Rev_VVIX":     pd.Series(sig_11, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "Mac_12_CuU2_GLDBull":   pd.Series(sig_12, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "Mac_13_FiltB2_NoFri":   pd.Series(sig_13, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "Mac_14_RR10_EMA3_Long": pd.Series(sig_14, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "Mac_15_RR50_ScaleU2":   pd.Series(sig_15, index=c.index).clip(-1, 1).shift(1).fillna(0)}

# ------------------------------------------------------------------------------
# 7. RATES & FX SIGNALS
# ------------------------------------------------------------------------------
def build_rates_fx_signals(df):
    if "Close_US10Y" not in df.columns: return {}
    o, h, l, c, v, ret, tr, vol20, vol60, vol_adj = compute_base(df)

    u10 = df["Close_US10Y"]
    u2 = df["Close_US2Y"]
    eur = df["Close_EUR"]
    uj = df["Close_UJ"]

    # US10Y
    rsi_diff = calc_rsi(c, 9) - calc_rsi(u10, 9)
    sig_1 = np.where(vol20 < vol20.rolling(277).median(), np.tanh(zscore(rsi_diff, 55)), 0).clip(0, 1)

    z_rr3 = zscore(c * u10, 11)
    b3 = np.where(u10.diff(50) < 0, np.sign(c.diff(50)), -np.sign(c.diff(50))) * vol_adj
    stop_m3 = ((b3 > 0) & (c < c.rolling(20).min().shift(1))) | ((b3 < 0) & (c > c.rolling(20).max().shift(1)))
    sig_2 = (-np.tanh(z_rr3).ewm(span=6).mean() + np.where(stop_m3, 0, b3)) / 2

    sig_3 = (-zscore(u10.diff(), 10).clip(-1, 1) + np.where((u10 - u10.ewm(span=55).mean()) < 0, np.sign(c.diff(50)), np.where((u10 - u10.ewm(span=55).mean()) > 0, -np.sign(c.diff(50)), 0)) * vol_adj) / 2

    # US2Y
    z10 = zscore(u2.diff(), 10)
    sig_4 = np.where(z10 > (1.75 + (u2 > u2.rolling(200).mean()) * 0.5), -1, np.where(z10 < -1.75, 1, 0))

    sig_5 = np.clip(-10 * (u2.pct_change() + (u2.pct_change() - u2.pct_change().shift(1))).ewm(span=3).mean(), -1, 1)

    r_skew = (c / u2).diff().rolling(21).skew()
    sig_6 = np.where(r_skew > 1.0, np.clip(zscore(c / u2, 10), -1, 1), 0)

    up2 = (u2.diff() > 0).astype(int)
    dn2 = (u2.diff() < 0).astype(int)
    strk_up = up2.groupby((up2 == 0).cumsum()).cumsum()
    strk_dn = dn2.groupby((dn2 == 0).cumsum()).cumsum()
    sig_7 = np.where(u2 < 1.0, np.where(strk_up >= 2, -1, np.where(strk_dn >= 2, 1, 0)), 0)

    b63 = ret.rolling(63).cov(u2.pct_change()) / u2.pct_change().rolling(63).var()
    sig_8 = np.where(np.abs(zscore(u2.diff(), 14)) > 1.5, -np.sign(zscore(u2.diff(), 14)), np.where(b63 > 0, np.sign(c.diff(63)), -np.sign(u2.diff(63))))

    # EUR/USD
    c50 = ret.rolling(50).corr(eur.pct_change())
    e_mom20 = eur.pct_change(20).abs()
    g_mom20 = c.pct_change(20).abs()
    atr14 = tr.rolling(14).mean()

    sig_9 = np.clip(np.where(c50 > 0, 1, np.where(c.pct_change(40) < 0.02, -1, 0)) * (e_mom20 / e_mom20.median()), -1, 1) * (atr14.median() / atr14)

    sig_10 = np.where(vol20 > vol20.median(), np.clip(np.where(c50 > 0, 1, np.where(c.pct_change(40) < 0, -1, 0)) * (g_mom20 / g_mom20.median()), -1, 1) * 0.5, np.clip(np.where(c50 > 0, 1, np.where(c.pct_change(40) < 0, -1, 0)) * (g_mom20 / g_mom20.median()), -1, 1))

    sig_11 = np.where(c.pct_change(20) * eur.pct_change(20) < 0, np.where(calc_rsi(eur, 14) > 75, 0, np.clip(ret.rolling(200).corr(eur.pct_change()) * 3, -1, 1)) * 0.5, np.where(calc_rsi(eur, 14) > 75, 0, np.clip(ret.rolling(200).corr(eur.pct_change()) * 3, -1, 1)))

    sig_12 = np.where(vol20 > vol20.median(), np.clip(np.where(c50 > 0, 1, np.where(c.pct_change(60) < 0, -1, 0)) * (g_mom20 / g_mom20.median()), -1, 1) * 0.5, np.clip(np.where(c50 > 0, 1, np.where(c.pct_change(60) < 0, -1, 0)) * (g_mom20 / g_mom20.median()), -1, 1))

    sig_13 = np.where(c.pct_change(20) * eur.pct_change(20) < 0, np.clip(np.clip(ret.rolling(100).corr(eur.pct_change()) * 3, -1, 1) * (vol20.median() / vol20), -1, 1) * 0.5, np.clip(np.clip(ret.rolling(100).corr(eur.pct_change()) * 3, -1, 1) * (vol20.median() / vol20), -1, 1))

    # USD/JPY
    cz = zscore(ret.rolling(60).corr(uj.pct_change()), 200)
    dn_vol = pd.Series(np.where(ret < 0, ret, 0), index=c.index).rolling(20).std()

    sig_14 = np.where((ret.rolling(60).corr(uj.pct_change()) > -0.1) & ~(c.pct_change(5) > 0.05), 1, 0) * np.clip(dn_vol.rolling(252).median() / dn_vol, 0.5, 1.5)

    sig_15 = np.where((c/uj).rolling(10).mean() > (c/uj).rolling(200).mean(), 1, 0) * np.clip(vol20.rolling(252).median() / vol20, 0.5, 1.5) * np.where(cz > 1, 1.5, 1.0)

    sig_16 = np.where(calc_rsi(c, 14) > calc_rsi(uj, 14), 1, 0) * np.clip(vol20.rolling(252).median() / vol20, 0.5, 1.5) * np.where(ret < 0, 1.5, 1.0)

    sig_17 = np.where((c.pct_change(60) > 0) & (uj.pct_change(60) < 0) & ((c*uj) > (c*uj).rolling(50).mean()), 1, 0) * np.where(cz > 1, 1.5, 1.0)

    sig_18 = np.where((ret.rolling(120).corr(uj.pct_change()) > -0.3) & (uj.pct_change().rolling(20).std() < uj.pct_change().rolling(20).std().rolling(252).median()) & (calc_chop(h, l, c, 14) < 50), 1, 0)

    return {
        "RFX_01_U10_RSI_Div_Long":   pd.Series(sig_1, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "RFX_02_U10_RealRates":      pd.Series(sig_2, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "RFX_03_U10_YieldMom":       pd.Series(sig_3, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "RFX_04_U2_YieldRev_Asym":   pd.Series(sig_4, index=c.index).shift(1).fillna(0),
        "RFX_05_U2_ContYield_EMA":   pd.Series(sig_5, index=c.index).shift(1).fillna(0),
        "RFX_06_U2_RatioTrend_Skew": pd.Series(sig_6, index=c.index).shift(1).fillna(0),
        "RFX_07_U2_YieldStreak":     pd.Series(sig_7, index=c.index).shift(1).fillna(0),
        "RFX_08_U2_BetaRegime_OR":   pd.Series(sig_8, index=c.index).shift(1).fillna(0),
        "RFX_09_EUR_RegMom40_ATR":   pd.Series(sig_9, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "RFX_10_EUR_RegMom40_Vol":   pd.Series(sig_10, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "RFX_11_EUR_Corr200_MacDiv": pd.Series(sig_11, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "RFX_12_EUR_RegMom60_Vol":   pd.Series(sig_12, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "RFX_13_EUR_Corr100_MacDiv": pd.Series(sig_13, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "RFX_14_UJ_Corr60_Breakout": pd.Series(sig_14, index=c.index).shift(1).fillna(0),
        "RFX_15_UJ_Ratio_MA":        pd.Series(sig_15, index=c.index).shift(1).fillna(0),
        "RFX_16_UJ_RSI_Spread":      pd.Series(sig_16, index=c.index).shift(1).fillna(0),
        "RFX_17_UJ_Safe_Haven":      pd.Series(sig_17, index=c.index).shift(1).fillna(0),
        "RFX_18_UJ_Corr120_Chop":    pd.Series(sig_18, index=c.index).shift(1).fillna(0)}

# ------------------------------------------------------------------------------
# 8. ASYMMETRIC VOLATILITY SIGNALS
# ------------------------------------------------------------------------------
def build_asym_vol_signals(df):
    o, h, l, c, v, ret, tr, vol20, vol60, vol_adj = compute_base(df)

    up_r = pd.Series(np.where(ret > 0, ret, 0), index=ret.index)
    dn_r = pd.Series(np.where(ret < 0, ret, 0), index=ret.index)

    crash_f = (ret < ret.rolling(60).quantile(0.05)).rolling(5).max() == 0
    no_fri = (df.index.dayofweek != 4).astype(int)
    rsi14 = calc_rsi(c, 14)

    vodvol = dn_r.rolling(10).var().rolling(20).std()
    vod_norm = 1 - (vodvol - vodvol.rolling(252).min()) / (vodvol.rolling(252).max() - vodvol.rolling(252).min() + 1e-8)
    sig_1 = np.where((up_r.rolling(10).var() > dn_r.rolling(10).var()) & crash_f, 1, 0) * vod_norm.clip(0, 1) * no_fri

    s2_rsi = np.where(ret.rolling(5).skew() > ret.rolling(20).skew(), 1, 0) * vol_adj.clip(0, 1) * (rsi14 < 70)
    sig_2 = np.where((s2_rsi == 0) & (ret.rolling(60).skew() < -1.0), -1.0, s2_rsi)

    kurt20 = ret.rolling(20).kurt()
    up20_v = up_r.rolling(20).var()
    s3_b = np.where(crash_f & (kurt20 < kurt20.rolling(252).quantile(0.9)), 1, 0) * (up20_v >= up20_v.rolling(20).max() * 0.95)
    sig_3 = np.where(rsi14 > 75, 0, s3_b)

    cmf20 = (((c - l) - (h - c)) / (h - l + 1e-8) * v).rolling(20).sum() / (v.rolling(20).sum() + 1e-8)
    sig_4 = np.where((ret.rolling(10).skew() > ret.rolling(120).skew()) & crash_f, 1, 0) * (cmf20 > 0) * no_fri

    z_up = zscore(up20_v, 252)
    z_kurt = zscore(kurt20, 252)
    risk_b = ~((z_up + z_kurt > 4) & (c > c.rolling(200).mean()))
    sig_5 = np.where(risk_b & crash_f, 1, 0) * (c / h.rolling(252).max()) * no_fri

    return {
        "Asym_01_VoDVol_NoFri":   pd.Series(sig_1, index=c.index).shift(1).fillna(0),
        "Asym_02_VolRSI_InvSkew": pd.Series(sig_2, index=c.index).shift(1).fillna(0),
        "Asym_03_UpBreak_RSIExh": pd.Series(sig_3, index=c.index).shift(1).fillna(0),
        "Asym_04_Mac_CMF_NoFri":  pd.Series(sig_4, index=c.index).shift(1).fillna(0),
        "Asym_05_RiskDist52W":    pd.Series(sig_5, index=c.index).shift(1).fillna(0)}

# ------------------------------------------------------------------------------
# 9. FIBONACCI SIGNALS
# ------------------------------------------------------------------------------
def build_fibonacci_signals(df):
    o, h, l, c, v, ret, tr, vol20, vol60, vol_adj = compute_base(df)

    rsi14 = calc_rsi(c, 14)
    bouncing = c > c.shift(1)

    pdm = np.where((h - h.shift(1)) > (l.shift(1) - l), np.maximum(h - h.shift(1), 0), 0)
    mdm = np.where((l.shift(1) - l) > (h - h.shift(1)), np.maximum(l.shift(1) - l, 0), 0)
    atr_adx = tr.rolling(14).mean()
    pdi = 100 * (pd.Series(pdm, index=c.index).rolling(14).mean() / atr_adx)
    mdi = 100 * (pd.Series(mdm, index=c.index).rolling(14).mean() / atr_adx)
    adx = (100 * abs(pdi - mdi) / (pdi + mdi + 1e-8)).rolling(14).mean()

    idx = np.arange(len(df))
    fibs = {}
    for w in[20, 60, 120, 252]:
        sh = h.rolling(w).max()
        sl = l.rolling(w).min()
        sh_idx = h.rolling(w).apply(np.argmax, raw=True) + idx - w + 1
        sl_idx = l.rolling(w).apply(np.argmin, raw=True) + idx - w + 1
        sdir = np.where(sh_idx > sl_idx, 1, -1)
        amp = sh - sl
        st = (c - sl) / (amp + 1e-8)
        fibs[w] = {"st": st, "sdir": sdir, "amp": amp, "sh": sh, "sl": sl}

    s1_cond = (fibs[120]["st"] > 0.382) & (fibs[120]["st"] < 0.618) & bouncing
    sig_1 = pd.Series(s1_cond, index=c.index).rolling(3).mean().fillna(0) * (rsi14 < 70) * (((c - l) / (h - l + 1e-8)) > 0.70)

    cg = sum(np.where((fibs[w]["st"] > 0.382) & (fibs[w]["st"] < 0.618) & bouncing, 1, 0) for w in [20, 60, 120, 252])
    sig_2 = pd.Series(cg / 4, index=c.index).rolling(3).mean().fillna(0) * (rsi14 < 70) * (adx / 100)

    s3_cond = (fibs[252]["st"] > 0) & (fibs[252]["st"] <= 0.382) & bouncing
    sig_3 = pd.Series(s3_cond, index=c.index).rolling(3).mean().fillna(0) * (rsi14 < 70) * (adx / 100)

    f0618 = np.where(fibs[20]["sdir"] == 1, fibs[20]["sh"] - 0.618 * fibs[20]["amp"], fibs[20]["sl"] + 0.618 * fibs[20]["amp"])
    c4l = (fibs[252]["sdir"] == 1) & (fibs[20]["sdir"] == -1) & (c > f0618)
    c4s = (fibs[252]["sdir"] == -1) & (fibs[20]["sdir"] == 1) & (c < f0618)
    sig_4 = np.where(c4l, 1, np.where(c4s, -1, 0)) * (c.pct_change(20) < 0) * (adx / 100)

    s5_cond = (fibs[120]["st"] > 0) & (fibs[120]["st"] <= 0.382) & bouncing
    sig_5 = pd.Series(s5_cond, index=c.index).rolling(3).mean().fillna(0) * (ret < 0) * (adx / 100)

    return {
        "Fib_01_GoldenBounce120": pd.Series(sig_1, index=c.index).shift(1).fillna(0),
        "Fib_02_ComboGolden_ADX": pd.Series(sig_2, index=c.index).shift(1).fillna(0),
        "Fib_03_DeepPull252_ADX": pd.Series(sig_3, index=c.index).shift(1).fillna(0),
        "Fib_04_MTF_Divergence":  pd.Series(sig_4, index=c.index).shift(1).fillna(0),
        "Fib_05_DeepPull120_Red": pd.Series(sig_5, index=c.index).shift(1).fillna(0)}

# ------------------------------------------------------------------------------
# 10. MARKET EFFICIENCY & NOISE SIGNALS
# ------------------------------------------------------------------------------
def build_efficiency_noise_signals(df):
    o, h, l, c, v, ret, tr, vol20, vol60, vol_adj = compute_base(df)

    logret = np.log(c / c.shift(1))
    er20 = calc_er(c, 20)
    z20 = zscore(c, 20)
    hv_rank = (vol20 - vol20.rolling(252).min()) / (vol20.rolling(252).max() - vol20.rolling(252).min() + 1e-8)

    sig_1 = np.where((er20 < 0.15) & (z20 > 1.5), 1, np.where((er20 < 0.15) & (z20 < -1.5), -1, 0))
    sig_1 = np.where(df.index.dayofweek == 4, 0, sig_1) * (1 - hv_rank)

    v_fast = logret.rolling(5).sum().rolling(120).var() / (logret.rolling(120).var() * 5 + 1e-8)
    v_slow = logret.rolling(10).sum().rolling(120).var() / (logret.rolling(120).var() * 10 + 1e-8)
    atr14 = tr.rolling(14).mean()
    chop_diff = calc_chop(h, l, c, 14).diff(5)
    sig_2 = np.sign(v_fast - v_slow) * np.sign(c.diff(10))
    sig_2 = np.where((atr14 > atr14.rolling(50).mean()) & (chop_diff < 0), sig_2, 0)

    nr = (c / o - 1).rolling(20).var() / ((o / c.shift(1) - 1).rolling(20).var() + 1e-8)
    sig_3 = np.where(nr > 1.0, -np.sign(ret), np.sign(ret))
    sig_3 = np.clip(np.where(sig_3 > 0, sig_3, 0) * (0.01 / (vol20 + 1e-8)), -1, 1)

    path20 = c.diff().abs().rolling(20).sum()
    sig_4 = np.where(c > l.rolling(20).min() + path20 * 0.2, 1, -1)
    runup = c / c.rolling(252).min() - 1
    sig_4 = np.where((sig_4 > 0) & (runup <= 0.20), sig_4, 0)

    sig_5 = np.where(calc_er(c, 252) > 0.1, np.sign(c.diff(252)), 0)
    sig_5 = np.where(v > v.rolling(20).mean(), sig_5, 0) * np.clip(1 - np.abs(z20)/3, 0, 1)

    return {
        "Eff_01_Noise_Breakout":   pd.Series(sig_1, index=c.index).shift(1).fillna(0),
        "Eff_02_VR_Accel":         pd.Series(sig_2, index=c.index).shift(1).fillna(0),
        "Eff_03_Intraday_NR":      pd.Series(sig_3, index=c.index).shift(1).fillna(0),
        "Eff_04_Channel_Breakout": pd.Series(sig_4, index=c.index).shift(1).fillna(0),
        "Eff_05_Trend252_Fade":    pd.Series(sig_5, index=c.index).shift(1).fillna(0)}

# ------------------------------------------------------------------------------
# 11. OVERNIGHT VS INTRADAY SIGNALS
# ------------------------------------------------------------------------------
def build_overnight_intraday_signals(df):
    o, h, l, c, v, ret, tr, vol20, vol60, vol_adj = compute_base(df)

    r_on = o / c.shift(1) - 1
    r_id = c / o - 1
    id_green = (c > o).astype(int)

    on_vol_20 = r_on.rolling(20).std() + 1e-6
    id_vol_20 = r_id.rolling(20).std() + 1e-6
    atr_14 = tr.rolling(14).mean()
    atr_14_pct = atr_14 / c

    on_sum_10 = r_on.rolling(10).sum()
    id_sum_10 = r_id.rolling(10).sum()
    on_sum_20 = r_on.rolling(20).sum()
    id_sum_20 = r_id.rolling(20).sum()

    on_rank_20 = on_sum_20.rolling(252).rank(pct=True)
    id_rank_20 = id_sum_20.rolling(252).rank(pct=True)
    on_rank_30 = r_on.rolling(30).sum().rolling(252).rank(pct=True)
    id_rank_30 = r_id.rolling(30).sum().rolling(252).rank(pct=True)

    close_loc = (c - l) / (h - l + 1e-6)

    gap_up = r_on > 0
    gap_dn = r_on < 0
    id_up = r_id > 0
    id_dn = r_id < 0
    gap_filled = np.where(gap_up, l < c.shift(1), np.where(gap_dn, h > c.shift(1), False))
    gap_dn_10 = gap_dn.astype(int).rolling(10).sum()

    macd = c.ewm(span=12, adjust=False).mean() - c.ewm(span=26, adjust=False).mean()
    rsi_14 = calc_rsi(c, 14)

    id_mom_10 = id_green.rolling(10).mean() * 2 - 1
    on_rev_20 = -(gap_up.astype(int)).rolling(20).mean() * 2 - 1
    combo_raw = (id_mom_10 + on_rev_20) / 2
    combo_z_60 = ((combo_raw - combo_raw.rolling(60).mean()) / (combo_raw.rolling(60).std() + 1e-6)).clip(-1, 1)

    sig_1 = np.where(id_green.rolling(10).sum() >= 8, 1, 0) * (1 / (id_vol_20 * 100 + 1)) * (tr > atr_14)

    sig_2 = np.where(id_green.rolling(5).sum() >= 4, 1, 0) * (1 / (on_vol_20 * 100 + 1))

    sig_3 = np.where((on_rank_20 < 0.3) & (id_rank_20 > 0.7), 1, 0) * (id_sum_10 > 0) * (~close_loc.between(0.4, 0.6))

    confirm = ((gap_up & id_up) | (gap_dn & id_dn))
    sig_4 = np.where((on_sum_20 > 0) & (id_sum_20 > 0), 1, 0) * confirm * (macd > 0)

    sig_5 = np.where((on_sum_10 < 0) & (id_sum_10 > 0), 1, 0) * (np.abs(r_on) > np.abs(r_id)) * (gap_dn_10 >= 6)

    sig_6 = np.where((on_rank_30 < 0.3) & (id_rank_30 > 0.7), 1, 0) * (~gap_filled) * (macd > 0)

    sig_7 = combo_z_60 * (id_sum_10 > 0) * (rsi_14 < 50)

    sig_8 = np.where((on_sum_10 < 0) & (id_sum_10 > 0), 1, np.where((on_sum_10 > 0) & (id_sum_10 < 0), -1, 0)) * (gap_dn_10 >= 6)

    sig_9 = np.where((on_sum_10 < 0) & (id_sum_10 < 0), 1, 0) * (c.index.dayofweek == 0) * (np.abs(ret) / atr_14_pct)

    sig_10 = np.where((on_sum_10 > 0) & (id_sum_10 > 0), 1, 0) * (c.index.dayofweek != 4) * (np.abs(ret) / atr_14_pct)

    return {
        "ONID_01_IDMom_TRVol":        pd.Series(sig_1, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "ONID_02_IDMom_ONVol":        pd.Series(sig_2, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "ONID_03_RankDiverge_IDMom":  pd.Series(sig_3, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "ONID_04_TrendConfirm_MACD":  pd.Series(sig_4, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "ONID_05_IDOverON_GapDn":     pd.Series(sig_5, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "ONID_06_RankDiverge30_MACD": pd.Series(sig_6, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "ONID_07_ComboZ60_IDMom":     pd.Series(sig_7, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "ONID_08_ONIDDiv_GapDn":      pd.Series(sig_8, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "ONID_09_BothDn_MonRev":      pd.Series(sig_9, index=c.index).clip(-1, 1).shift(1).fillna(0),
        "ONID_10_BothUp_NoFri":       pd.Series(sig_10, index=c.index).clip(-1, 1).shift(1).fillna(0)}

# ------------------------------------------------------------------------------
# 12. GAPS SIGNALS
# ------------------------------------------------------------------------------
def build_gap_signals(df):
    o, h, l, c, v, ret, tr, vol20, vol60, vol_adj = compute_base(df)

    gap = o / c.shift(1) - 1
    atr_14 = tr.rolling(14).mean() / c.shift(1)
    gap_norm = gap / (atr_14 + 1e-8)

    gap_kurt = gap.rolling(20).kurt()
    gap_skew = gap.rolling(20).skew()
    vol_z = zscore(v, 50)

    no_fri = c.index.dayofweek != 4
    rng_cont = tr <= (tr.rolling(14).mean())
    gap_decel = gap.abs() < gap.abs().shift(1)

    gap_abs_ema = gap.abs().ewm(span=10).mean()
    ema_compress = gap_abs_ema < gap_abs_ema.rolling(50).median()
    ret_skew = ret.rolling(20).skew()

    sig_1 = np.where((gap_kurt > 3.0) & no_fri & (vol_z < 1.0), -1, np.where(no_fri & (vol_z < 1.0), 1, 0))

    sig_2 = np.where((gap < -0.001) & rng_cont & gap_decel, 1, 0)

    sig_3 = np.where((gap_skew > 1.0) & no_fri & (vol_z < 1.0), -1, np.where(no_fri & (vol_z < 1.0), 1, 0))

    sig_4 = np.where((gap_norm < 0.7) & no_fri & (vol_z < 1.0), 1, 0)

    sig_5 = np.where((gap_kurt > 2.0) & no_fri & ema_compress, -1, np.where(no_fri & ema_compress, 1, 0))

    sma_50 = c.rolling(50).mean()
    cond_exh_up = (c.shift(1) > 1.05 * sma_50.shift(1)) & (gap > 0.005)
    cond_exh_dn = (c.shift(1) < 0.95 * sma_50.shift(1)) & (gap < -0.005)
    sig_6_base = np.where(cond_exh_up, -1, np.where(cond_exh_dn, 1, 0))
    sig_6_series = pd.Series(sig_6_base, index=c.index)
    sig_6 = np.where((sig_6_series == sig_6_series.shift(1)) & (ret_skew < 0), sig_6_base, 0)

    return {
        "Gap_01_Kurt3_Fade_NoFri":  pd.Series(sig_1, index=c.index).shift(1).fillna(0),
        "Gap_02_MinGapDn_Buy":      pd.Series(sig_2, index=c.index).shift(1).fillna(0),
        "Gap_03_Skew1_Fade_NoFri":  pd.Series(sig_3, index=c.index).shift(1).fillna(0),
        "Gap_04_Continuation_Tight":pd.Series(sig_4, index=c.index).shift(1).fillna(0),
        "Gap_05_Kurt2_VolComp":     pd.Series(sig_5, index=c.index).shift(1).fillna(0),
        "Gap_06_Exhaustion_Rev":    pd.Series(sig_6, index=c.index).shift(1).fillna(0)}

# ------------------------------------------------------------------------------
# 13. VOLATILITY MOMENTUM SIGNALS
# ------------------------------------------------------------------------------
def build_volatility_momentum_signals(df):
    o, h, l, c, v, ret, tr, vol20, vol60, vol_adj = compute_base(df)

    parkinson = np.sqrt((1 / (4 * np.log(2))) * (np.log(h / l) ** 2)) * np.sqrt(252)
    rv_5 = ret.rolling(5).std() * np.sqrt(252)
    rv_20 = ret.rolling(20).std() * np.sqrt(252)

    sma_50 = c.rolling(50).mean()
    bbw = (4 * c.rolling(20).std()) / c.rolling(20).mean()
    bbw_rank_100 = bbw.rolling(100).rank(pct=True)

    mom_20 = c.pct_change(20)
    autocorr_20 = ret.rolling(20).corr(ret.shift(1))

    park_ma_50 = pd.Series(parkinson).rolling(50).mean()
    sig_1 = np.where((parkinson < park_ma_50) & (c.index.dayofweek != 4) & (ret.shift(1) < 0), 1, 0)

    sig_2 = np.where((rv_5 / rv_5.shift(1)) > 1.1, 1, 0) * np.where(c > sma_50, 1.0, 0.5)

    sig_3 = np.where((rv_20 > rv_20.rolling(252).quantile(0.95)) & (autocorr_20 > 0), 1, 0)

    vol_trend_200 = rv_20.rolling(200).mean().diff(20)
    sig_4 = np.where((vol_trend_200 < 0) & (mom_20 > 0), 1, 0) * (1 - bbw_rank_100).fillna(0)

    return {
        "VMom_01_Parkinson_Drop_Buy":    pd.Series(sig_1, index=c.index).shift(1).fillna(0),
        "VMom_02_FastSpike_BearSizing":  pd.Series(sig_2, index=c.index).shift(1).fillna(0),
        "VMom_03_ExtremeBO_TrendPersist":pd.Series(sig_3, index=c.index).shift(1).fillna(0),
        "VMom_04_VolTrendDn_BBWSizing":  pd.Series(sig_4, index=c.index).shift(1).fillna(0)}

# ------------------------------------------------------------------------------
# 14. AUTOCORRELATION SIGNALS
# ------------------------------------------------------------------------------
def build_autocorrelation_signals(df):
    o, h, l, c, v, ret, tr, vol20, vol60, vol_adj = compute_base(df)

    ma_200 = c.rolling(200).mean()
    z_5 = (ret - ret.rolling(5).mean()) / (ret.rolling(5).std() + 1e-6)
    vol_pct = vol20.rolling(252).rank(pct=True)
    gap = o / c.shift(1) - 1

    macd = c.ewm(span=12).mean() - c.ewm(span=26).mean()
    macd_sig = macd.ewm(span=9).mean()
    wick = (c - l) / (h - l + 1e-6)

    sign_ret = np.sign(ret)
    sign_change = sign_ret != sign_ret.shift(1)
    run_len_abs = sign_ret.groupby(sign_change.cumsum()).cumcount() + 1
    run_length = run_len_abs * sign_ret

    sig_1_base = pd.Series(np.where((c > ma_200) & (ret < 0), -z_5, 0), index=c.index).clip(0, 1)
    sig_1_base = sig_1_base * np.where(vol20 < vol20.shift(5), 1, 0)
    sig_1 = (0.5 * sig_1_base + 0.25 * sig_1_base.shift(1).fillna(0) + 0.125 * sig_1_base.shift(2).fillna(0))

    sig_2_base = pd.Series(np.where((c > ma_200) & (ret < 0), 1, 0), index=c.index)
    sig_2_base = sig_2_base * np.where(vol20 < vol20.shift(5), 1, 0)
    sig_2 = np.where(gap > 0, sig_2_base.clip(-1, 0.5), sig_2_base)

    med_vol = vol20.rolling(252).median()
    sig_3_base = pd.Series(np.where(vol20 > med_vol, -np.sign(ret), np.sign(ret)), index=c.index)
    sig_3_base = (sig_3_base + sig_3_base.shift(1).fillna(0) + sig_3_base.shift(2).fillna(0)) / 3
    sig_3 = sig_3_base * np.where(c.ewm(span=50).mean() > c.ewm(span=200).mean(), 1, 0)

    sig_4_base = pd.Series(np.where((vol_pct > 0.5) & (ret < 0), 1, 0), index=c.index)
    sig_4_base = sig_4_base * np.where(np.sign(gap) != np.sign(sig_4_base), 1, 0)
    sig_4 = sig_4_base.ewm(span=5).mean()

    sigA = np.where((vol_pct > 0.5) & (vol_pct <= 0.75) & (ret < 0), 1, 0)
    sigB = np.where((vol_pct > 0.75) & (run_length >= 2), -1, 0)
    sigC = np.where((vol_pct <= 0.5), np.sign(ret), 0)
    sig_5_base = pd.Series(sigA + sigB + sigC, index=c.index).clip(-1, 1)
    sig_5_base = sig_5_base * np.where(wick > 0.5, 1, 0)
    sig_5 = sig_5_base.ewm(span=5).mean()

    vol_ma = v.rolling(20).mean()
    sig_6_base = pd.Series(np.where((ret < 0) & (v <= vol_ma), 1, 0), index=c.index)
    sig_6 = sig_6_base.ewm(span=5).mean()

    streak = (ret < 0) & (ret.shift(1) < 0) & (ret.shift(2) < 0)
    sig_7_base = pd.Series(np.where((c > ma_200) & streak & (macd > macd_sig), 1, 0), index=c.index)
    ac = ret.rolling(20).corr(ret.shift(1))
    sig_7 = sig_7_base * np.where(ac.diff() > 0, 1, 0)

    return {
        "ACor_01_UpTrend_DipScale_Dyn": pd.Series(sig_1, index=c.index).shift(1).fillna(0),
        "ACor_02_UpTrend_DipBuy_Gap":   pd.Series(sig_2, index=c.index).shift(1).fillna(0),
        "ACor_03_VolCond_EMA_Cross":    pd.Series(sig_3, index=c.index).shift(1).fillna(0),
        "ACor_04_HighVol_DipBuy_EMA5":  pd.Series(sig_4, index=c.index).shift(1).fillna(0),
        "ACor_05_Ensemble_Wick_EMA5":   pd.Series(sig_5, index=c.index).shift(1).fillna(0),
        "ACor_06_AsymRev_VolDry_EMA5":  pd.Series(sig_6, index=c.index).shift(1).fillna(0),
        "ACor_07_UpTrend_Dn3_MACD":     pd.Series(sig_7, index=c.index).shift(1).fillna(0)}

# ------------------------------------------------------------------------------
# 15. LOW RV SIGNALS
# ------------------------------------------------------------------------------
def build_low_rv_signals(df):
    o, h, l, c, v, ret, tr, vol20, vol60, vol_adj = compute_base(df)

    sma5 = c.rolling(5).mean()
    sma20 = c.rolling(20).mean()
    sma60 = c.rolling(60).mean()

    rv10 = ret.rolling(10).std() * np.sqrt(252)
    rv20 = ret.rolling(20).std() * np.sqrt(252)
    rv60 = ret.rolling(60).std() * np.sqrt(252)
    rv252 = ret.rolling(252).std() * np.sqrt(252)

    rv20_pct = rv20.rolling(252).rank(pct=True)
    ts10_60 = rv10 / (rv60 + 1e-8)
    rv60_roc20 = rv60.pct_change(20)
    atr14 = (h - l).rolling(14).mean()

    sig_1_base = np.where((rv20_pct < 0.40) & (c > sma20) & (rv252 < rv252.shift(60)), 1, 0)
    sig_1_vol_target = np.clip(0.10 / (rv20 + 1e-8), 0, 1)
    sig_1 = sig_1_base * sig_1_vol_target

    sig_2_base = np.where(rv20_pct < 0.40, np.where(c > sma20, 1, -1), 0)
    sig_2 = sig_2_base * np.where((rv60_roc20 < 0) & (rv252 < rv252.shift(60)), 1, 0)

    sig_3_c1 = rv20_pct < 0.50
    sig_3_c2 = c > sma20
    sig_3_c3 = (h - l) > atr14
    sig_3_z = (c - sma20) / (c.rolling(20).std() + 1e-8)
    sig_3_c4 = sig_3_z < 2.0
    sig_3_base = np.where(sig_3_c1, np.where(sig_3_c2, 1, -1), 0)
    sig_3 = sig_3_base * np.where(sig_3_c3 & sig_3_c4, 1, 0)

    sig_4_c1 = ts10_60 < 0.70
    sig_4_c2 = c > sma5
    sig_4_c3 = c < sma60
    sig_4_base = np.where(sig_4_c1 & sig_4_c3, np.where(sig_4_c2, 1, -1), 0)
    atr_norm = (atr14.rolling(252).min() / (atr14 + 1e-8)).clip(0, 1)
    sig_4 = sig_4_base * atr_norm

    return {
        "LRV_01_Trend_VolTarget":    pd.Series(sig_1, index=c.index).shift(1).fillna(0),
        "LRV_02_SymTrend_MacroCont": pd.Series(sig_2, index=c.index).shift(1).fillna(0),
        "LRV_03_SymTrend_ATRExp":    pd.Series(sig_3, index=c.index).shift(1).fillna(0),
        "LRV_04_TermStruct_MeanRev": pd.Series(sig_4, index=c.index).shift(1).fillna(0)}

# ------------------------------------------------------------------------------
# 16. HIGH VIX SIGNALS
# ------------------------------------------------------------------------------
def build_high_vix_signals(df):
    if "Close_VIX" not in df.columns: return {}
    o, h, l, c, v, ret, tr, vol20, vol60, vol_adj = compute_base(df)

    v_c = df["Close_VIX"]
    v_o = df.get("Open_VIX", v_c)
    v_h = df.get("High_VIX", v_c)
    v_l = df.get("Low_VIX", v_c)

    v_ma_10 = v_c.rolling(10).mean()
    v_ma_50 = v_c.rolling(50).mean()

    sig_1 = pd.Series(0.0, index=c.index)
    sig_1_cond = v_h > 30
    sig_1 = np.where(sig_1_cond, np.clip((v_o / (v_c + 1e-5) - 1) * 15, 0, 1), 0)
    sig_1 = pd.Series(sig_1, index=c.index) * (ret < 0)
    sig_1_final = (sig_1 + sig_1.shift(1).fillna(0) * 0.5).clip(-1, 1)

    sig_2 = pd.Series(0.0, index=c.index)
    sig_2 = np.where(sig_1_cond, np.clip((v_o / (v_c + 1e-5) - 1) * 10, 0, 1), 0)
    sig_2 = pd.Series(sig_2, index=c.index) * (ret < 0)
    sig_2_final = (sig_2 + sig_2.shift(1).fillna(0) * 0.5).clip(-1, 1)

    sig_3 = pd.Series(0.0, index=c.index)
    sig_3_cond = (v_h > 20) & (v_c < v_o * 0.95)
    sig_3 = np.where(sig_3_cond, 1.0, 0.0)
    sig_3 = pd.Series(sig_3, index=c.index) * (v_ma_10 > v_ma_50)
    sig_3_final = (sig_3 * (30 / (v_c + 1e-5))).clip(-1, 1)

    sig_4_cond = v_h > 20
    sig_4 = np.where(sig_4_cond, np.clip((v_o / (v_c + 1e-5) - 1) * 5, 0, 1), 0)
    sig_4 = pd.Series(sig_4, index=c.index) * (v_ma_10 > v_ma_50)
    sig_4_final = (sig_4 * (0.01 / (vol20 + 1e-5))).clip(-1, 1)

    sig_5 = np.where(sig_1_cond, np.clip((v_o / (v_c + 1e-5) - 1) * 5, 0, 1), 0)
    sig_5 = pd.Series(sig_5, index=c.index) * (ret < 0)
    sig_5_final = (sig_5 + sig_5.shift(1).fillna(0) * 0.5).clip(-1, 1)

    sig_6 = np.where(sig_4_cond, np.clip((v_o / (v_c + 1e-5) - 1) * 10, 0, 1), 0)
    sig_6 = pd.Series(sig_6, index=c.index) * (v_ma_10 > v_ma_50)
    sig_6_final = (sig_6 * (30 / (v_c + 1e-5))).clip(-1, 1)

    sig_7 = np.where(sig_4_cond, np.clip((v_o / (v_c + 1e-5) - 1) * 15, 0, 1), 0)
    sig_7 = pd.Series(sig_7, index=c.index) * (v_ma_10 > v_ma_50)
    sig_7_final = (sig_7 * (30 / (v_c + 1e-5))).clip(-1, 1)

    sig_8 = np.where(v_h > 15, np.clip((v_o / (v_c + 1e-5) - 1) * 5, 0, 1), 0)
    sig_8 = pd.Series(sig_8, index=c.index) * (v_ma_10 > v_ma_50)
    sig_8_final = (sig_8 + sig_8.shift(1).fillna(0) * 0.5).clip(-1, 1)

    return {
        "HVIX_01_Cont30_M15_MomDecay":   pd.Series(sig_1_final, index=c.index).shift(1).fillna(0),
        "HVIX_02_Cont30_M10_MomDecay":   pd.Series(sig_2_final, index=c.index).shift(1).fillna(0),
        "HVIX_03_Bin20_DropTerm_InvVIX": pd.Series(sig_3_final, index=c.index).shift(1).fillna(0),
        "HVIX_04_Cont20_M5_Term_GLDVol": pd.Series(sig_4_final, index=c.index).shift(1).fillna(0),
        "HVIX_05_Cont30_M5_MomDecay":    pd.Series(sig_5_final, index=c.index).shift(1).fillna(0),
        "HVIX_06_Cont20_M10_Term_InvVIX":pd.Series(sig_6_final, index=c.index).shift(1).fillna(0),
        "HVIX_07_Cont20_M15_Term_InvVIX":pd.Series(sig_7_final, index=c.index).shift(1).fillna(0),
        "HVIX_08_Cont15_M5_Term_Decay":  pd.Series(sig_8_final, index=c.index).shift(1).fillna(0)}

# ------------------------------------------------------------------------------
# 17. BEAR SIGNALS
# ------------------------------------------------------------------------------
def build_bear_signals(df):
    o, h, l, c, v, ret, tr, vol20, vol60, vol_adj = compute_base(df)

    sma200 = c.rolling(200).mean()
    high252 = h.rolling(252).max()
    dd252 = (c - high252) / (high252 + 1e-8)
    low20 = l.rolling(20).min().shift(1)

    ema12 = c.ewm(span=12, adjust=False).mean()
    ema26 = c.ewm(span=26, adjust=False).mean()
    macd = ema12 - ema26
    macd_sig = macd.ewm(span=9, adjust=False).mean()
    macd_bull = macd > macd_sig
    bear_regime = c < sma200

    dist = (c - sma200) / (sma200 + 1e-8)
    sig_1 = np.where(dist < 0, -np.clip(dist * 5.0, -1, 1), 0)

    sig_2 = np.where((dd252 < -0.08) & macd_bull, 1, 0)

    vol_thresh = vol20.rolling(252).quantile(0.40)
    sig_3_base = np.where(bear_regime & (vol20 < vol_thresh) & (c < low20), -1, 0)
    streak_down = (ret < 0) & (ret.shift(1) < 0)
    sig_3 = np.where(streak_down, sig_3_base, 0)

    ret_10 = c.pct_change(10)
    sig_4 = np.where(bear_regime & (ret_10 < -0.10), 1, 0)

    return {
        "Bear_01_DistFade_SMA200_Scale5":  pd.Series(sig_1, index=c.index).shift(1).fillna(0),
        "Bear_02_Capitulation_8_MACDBull": pd.Series(sig_2, index=c.index).shift(1).fillna(0),
        "Bear_03_LowVol_Breakdown40th":    pd.Series(sig_3, index=c.index).shift(1).fillna(0),
        "Bear_04_MR_Drop_10d_10":          pd.Series(sig_4, index=c.index).shift(1).fillna(0)}

# ------------------------------------------------------------------------------
# 18. LOW VIX SIGNALS
# ------------------------------------------------------------------------------
def build_low_vix_signals(df):
    if "Close_VIX" not in df.columns: return {}
    o, h, l, c, v, ret, tr, vol20, vol60, vol_adj = compute_base(df)

    vix = df["Close_VIX"]
    no_fri = np.where(c.index.dayofweek != 4, 1, 0)

    g_ret = c.pct_change(20)
    v_ret = vix.pct_change(20)
    g_vol = ret.rolling(20).std()
    v_vol = vix.pct_change().rolling(20).std()
    sig_4 = np.where((g_ret / (g_vol + 1e-5)) > (v_ret / (v_vol + 1e-5)), 1, 0) * no_fri

    sig_1 = np.clip(vix.rolling(200).mean() / vix, 0, 1) * no_fri

    sig_2 = np.clip(vix.rolling(50).mean() / vix, 0, 1) * no_fri

    sig_3 = np.clip(0.15 / (vol20 + 1e-8), 0, 1) * np.where(vix < vix.rolling(200).mean(), 1, 0) * no_fri

    ema_short = c.ewm(span=12, adjust=False).mean()
    ema_long = c.ewm(span=26, adjust=False).mean()
    base_scale = np.clip(vix.rolling(50).mean() / vix, 0, 1)
    sig_5 = np.where(ema_short > ema_long, base_scale, 0) * no_fri

    v_rsi = calc_rsi(vix, 14)
    sig_6 = np.where(v_rsi < 50, 1, 0) * no_fri

    v_skew = vix.pct_change().rolling(20).skew()
    g_ma50 = c.rolling(50).mean()
    sig_7 = np.where((v_skew > 0) & (c > g_ma50), 1, 0) * no_fri

    v_ema_s = vix.ewm(span=12, adjust=False).mean()
    v_ema_l = vix.ewm(span=26, adjust=False).mean()
    v_macd = v_ema_s - v_ema_l
    v_sig = v_macd.ewm(span=9, adjust=False).mean()
    sig_8 = np.where(v_macd < v_sig, 1, 0) * no_fri

    low_min = vix.rolling(14).min()
    high_max = vix.rolling(14).max()
    v_k = 100 * (vix - low_min) / (high_max - low_min + 1e-8)
    sig_9 = np.where(v_k < 50, 1, 0) * no_fri

    g_rsi = calc_rsi(c, 14)
    sig_10 = np.where(g_rsi > v_rsi, 1, 0) * no_fri

    return {
        "LVIX_01_Adaptive_Inv_VIX":      pd.Series(sig_1, index=c.index).shift(1).fillna(0),
        "LVIX_02_Smoothed_Inv_VIX":      pd.Series(sig_2, index=c.index).shift(1).fillna(0),
        "LVIX_03_Vol_Target_Scaling200": pd.Series(sig_3, index=c.index).shift(1).fillna(0),
        "LVIX_04_RiskAdj_Momentum":      pd.Series(sig_4, index=c.index).shift(1).fillna(0),
        "LVIX_05_Scaled_VIX_MACD":       pd.Series(sig_5, index=c.index).shift(1).fillna(0),
        "LVIX_06_VIX_RSI_LT_50":         pd.Series(sig_6, index=c.index).shift(1).fillna(0),
        "LVIX_07_VIX_SkewPos_Uptrend":   pd.Series(sig_7, index=c.index).shift(1).fillna(0),
        "LVIX_08_VIX_MACD_Bearish":      pd.Series(sig_8, index=c.index).shift(1).fillna(0),
        "LVIX_09_VIX_Stoch_LT_50":       pd.Series(sig_9, index=c.index).shift(1).fillna(0),
        "LVIX_10_GLD_RSI_GT_VIX_RSI":    pd.Series(sig_10, index=c.index).shift(1).fillna(0)}

# ------------------------------------------------------------------------------
# 19. EXECUTION & EVALUATION
# ------------------------------------------------------------------------------

if __name__ == "__main__":
    # Load all data
    df = load_data()

    # Build all signals
    signals_dict = {
        **build_seasonal_signals(df),
        **build_volume_signals(df),
        **build_breadth_base_signals(df),
        **build_macro_breadth_signals(df),
        **build_rates_fx_signals(df),
        **build_asym_vol_signals(df),
        **build_fibonacci_signals(df),
        **build_efficiency_noise_signals(df),
        **build_overnight_intraday_signals(df),
        **build_gap_signals(df),
        **build_volatility_momentum_signals(df),
        **build_autocorrelation_signals(df),
        **build_low_rv_signals(df),
        **build_high_vix_signals(df),
        **build_bear_signals(df),
        **build_low_vix_signals(df)}

    ret = df["Close"].pct_change()
    train = (df.index >= "2004-11-18") & (df.index <= "2018-12-31")
    test  = (df.index >= "2019-01-01") & (df.index <= "2023-12-31")

    def sharpe(r):
        r = r.fillna(0)
        return r.mean() / r.std() * np.sqrt(252) if r.std() > 0 else 0

    print(f"{"Signal":<35} | {"Train":>8} | {"Test":>8}")
    print("-" * 57)

    for name in sorted(signals_dict.keys()):
        r = signals_dict[name] * ret
        print(f"{name:<35} | {sharpe(r[train]):>8.2f} | {sharpe(r[test]):>8.2f}")