# -*- coding: utf-8 -*-
"""cycle_1_signals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15wxXRnihPctepoL1DptiFD93UpqHF0R0
"""

import pandas as pd
import numpy as np
import scipy.stats
import itertools
from itertools import product
from pandas.tseries.holiday import USFederalHolidayCalendar
import warnings
import os
from google.colab import drive

warnings.filterwarnings('ignore')


# ==============================================================================
# 1. DATA LOADING SECTION
# ==============================================================================
class DataLoader:
    """
    Easily adjustable Data Loader.
    Assumes GLD, VIX, and VVIX are the core datasets.
    Can be expanded to load SQL, APIs, or other CSVs dynamically.
    """
    def __init__(self, data_paths=None):
        # Default paths (update these to your local or drive paths)
        self.data_paths = data_paths or {
            "GLD": "GLD_Train_val.csv",
            "VIX": "df_VIX_Train_val.csv",
            "VVIX": "df_VVIX_Train_val.csv"
        }
        self.datasets = {}

    def load_data(self):
        print("Initializing Data Ingestion...")

        if not os.path.exists("/content/drive/My Drive"):
            drive.mount("/content/drive")

        base_path = "/content/drive/My Drive/Prometheus/First cycle/"

        for asset, file_name in self.data_paths.items():
            path = os.path.join(base_path, file_name)
            try:
                df = pd.read_csv(path, index_col="Date", parse_dates=True)
                df = df[~df.index.duplicated(keep="first")].sort_index()
                self.datasets[asset] = df
                print(f"  [+] Successfully loaded {asset}")
            except FileNotFoundError:
                if asset == "GLD":
                    raise FileNotFoundError(f"Could not find the main GLD file at {path}.")
                print(f"  [!] File {path} not found. Generating dummy data for {asset} to maintain framework execution...")
                dates = self.datasets["GLD"].index.copy()
                dummy = pd.DataFrame(index=dates)
                dummy["Open"] = np.random.uniform(10, 40, len(dates))
                dummy["High"] = dummy["Open"] * 1.01
                dummy["Low"] = dummy["Open"] * 0.99
                dummy["Close"] = np.random.uniform(10, 40, len(dates))
                dummy["Volume"] = np.random.randint(1000, 1000000, len(dates))
                self.datasets[asset] = dummy

        return self.datasets

TRAIN_START = "2004-11-18"
TRAIN_END = "2018-12-31"
TEST_START = "2019-01-01"
TEST_END = "2023-12-31"


# ==============================================================================
# 2. SHARED UTILITIES SECTION
# ==============================================================================
class SharedUtils:
    """Standardized quantitative functions accessible globally."""

    @staticmethod
    def calc_metrics_standard(returns, risk_free_rate=0.0):
        """Standardized performance measurement used as fallback."""
        returns = returns.dropna()
        if len(returns) < 2 or returns.std() == 0:
            return 0.0, 0.0, 0.0, 0.0, 0.0
        mean_ret = returns.mean() * 252
        vol = returns.std() * np.sqrt(252)
        sharpe = (mean_ret - risk_free_rate) / vol if vol > 0 else 0
        downside = returns[returns < 0]
        down_vol = downside.std() * np.sqrt(252)
        sortino = (mean_ret - risk_free_rate) / down_vol if down_vol > 0 else 0
        cum_ret = (1 + returns).cumprod()
        rolling_max = cum_ret.cummax()
        drawdown = (cum_ret - rolling_max) / rolling_max
        max_dd = drawdown.min() if len(drawdown) > 0 else 0
        calmar = mean_ret / abs(max_dd) if abs(max_dd) > 0 else 0
        tot_ret = cum_ret.iloc[-1] - 1 if len(cum_ret) > 0 else 0
        return sharpe, calmar, sortino, tot_ret, max_dd


# ==============================================================================
# 3. DYNAMIC SIGNAL REGISTRY & BASE CLASS
# ==============================================================================
class BaseSignalFamily:
    def __init__(self, data_dict):
        # Deep copies to prevent cross-family contamination
        self.df = data_dict.get('GLD').copy() if 'GLD' in data_dict else None
        self.vix = data_dict.get('VIX').copy() if 'VIX' in data_dict else None
        self.vvix = data_dict.get('VVIX').copy() if 'VVIX' in data_dict else None

        self.signals = {}
        self.results =[]
        self.signal_count = 0
        self.family_name = self.__class__.__name__

    def run(self):
        """Standardized execution cycle."""
        if self.df is None or self.df.empty:
            print(f"  [!] Missing primary data for {self.family_name}. Skipping.")
            return 0,[]

        self.generate_signals()
        self.evaluate_signals()
        return self.signal_count, self.results

    def generate_signals(self):
        pass

    def evaluate_signals(self):
        """Evaluates all registered signals strictly utilizing 1-day shifted exposures to prevent lookahead."""
        train_mask = (self.df.index >= '2004-11-18') & (self.df.index <= '2018-12-31')
        test_mask = (self.df.index >= '2019-01-01') & (self.df.index <= '2023-12-31')

        if 'Ret' not in self.df.columns:
            self.df['Ret'] = self.df['Close'].pct_change()

        for name, sig in self.signals.items():
            if isinstance(sig, np.ndarray):
                sig = pd.Series(sig, index=self.df.index)

            # The standard evaluation: shift(1) ensures the signal produced at T is traded at T+1
            strat_ret = sig.shift(1).fillna(0).clip(-1, 1) * self.df['Ret']

            tr_sh, tr_cal, tr_sor, tr_tot, tr_mdd = SharedUtils.calc_metrics_standard(strat_ret.loc[train_mask])
            te_sh, te_cal, te_sor, te_tot, te_mdd = SharedUtils.calc_metrics_standard(strat_ret.loc[test_mask])

            self.results.append({
                'Family': self.family_name, 'Signal': name,
                'Train Sharpe': round(tr_sh, 3), 'Test Sharpe': round(te_sh, 3),
                'Train Ret': round(tr_tot, 3), 'Test Ret': round(te_tot, 3),
                'Train DD': round(tr_mdd, 3), 'Test DD': round(te_mdd, 3)
            })
            self.signal_count += 1


# ==============================================================================
# 4. SIGNAL FAMILIES (1 TO 15)
# ==============================================================================

class LongTermTrendSignals(BaseSignalFamily):
    def generate_signals(self):
        df = self.df
        df['Ret'] = df['Close'].pct_change()

        def lin_reg_score(y):
            x = np.arange(len(y))
            var_x = ((x - x.mean())**2).sum()
            if var_x == 0: return 0
            cov = ((x - x.mean()) * (y - y.mean())).sum()
            var_y = ((y - y.mean())**2).sum()
            if var_y == 0: return 0
            r = cov / np.sqrt(var_x * var_y + 1e-8)
            return r * np.sign(cov / var_x)

        vol60 = df['Ret'].rolling(60).std() * np.sqrt(252)
        vol54 = df['Ret'].rolling(54).std() * np.sqrt(252)
        vol66 = df['Ret'].rolling(66).std() * np.sqrt(252)
        vol252 = df['Ret'].rolling(252).std() * np.sqrt(252)
        skew252 = df['Ret'].rolling(252).skew()

        vol_scale = np.clip(0.15 / (vol60 + 1e-4), 0.2, 2.0)
        v_scale_m10 = np.clip(0.15 / (vol54 + 1e-4), 0.2, 2.0)
        v_scale_p10 = np.clip(0.15 / (vol66 + 1e-4), 0.2, 2.0)

        mom_120 = df['Close'].pct_change(120) / (vol252 + 1e-4)
        mom_252 = df['Close'].pct_change(252) / (vol252 + 1e-4)
        Dual_Mom = np.clip(((np.tanh(mom_120 * 2) + np.tanh(mom_252 * 2)) / 2) * vol_scale, -1, 1)

        rs_180 = df['Close'].rolling(180).apply(lin_reg_score, raw=True)
        sig_lr_180 = np.clip(rs_180 * v_scale_m10 * 2, -1, 1)
        rs_200 = df['Close'].rolling(200).apply(lin_reg_score, raw=True)
        LinReg_200 = pd.Series(np.clip(rs_200 * vol_scale * 2, -1, 1), index=df.index)
        rs_220 = df['Close'].rolling(220).apply(lin_reg_score, raw=True)
        sig_lr_220 = np.clip(rs_220 * v_scale_p10 * 2, -1, 1)

        rib_180 = sum(np.where(df['Close'] > df['Close'].rolling(i).mean(), 1, -0.2) for i in range(45, 185, 9)) / 16
        sig_rib_180 = pd.Series(np.clip(rib_180 * v_scale_m10, -1, 1), index=df.index)
        rib_200 = sum(np.where(df['Close'] > df['Close'].rolling(i).mean(), 1, -0.2) for i in range(50, 210, 10)) / 16
        sig_rib_200 = pd.Series(np.clip(rib_200 * vol_scale, -1, 1), index=df.index)
        rib_220 = sum(np.where(df['Close'] > df['Close'].rolling(i).mean(), 1, -0.2) for i in range(55, 225, 11)) / 16
        sig_rib_220 = pd.Series(np.clip(rib_220 * v_scale_p10, -1, 1), index=df.index)

        Blend_m10 = (sig_lr_180 + sig_rib_180) / 2
        Blend_p10 = (sig_lr_220 + sig_rib_220) / 2

        min252 = df['Close'].rolling(252).min()
        max252 = df['Close'].rolling(252).max()
        donch = 2 * ((df['Close'] - min252) / (max252 - min252 + 1e-4)) - 1
        Smooth_Donchian = np.clip(donch.ewm(span=50).mean() * vol_scale, -1, 1)

        dist200 = df['Close'] / df['Close'].rolling(200).mean() - 1
        dist200_z = dist200 / (dist200.rolling(252).std() + 1e-4)
        z_dist_200ma = np.clip(np.tanh(dist200_z) * vol_scale, -1, 1)
        Asym_ZDist = pd.Series(np.where(z_dist_200ma > 0, z_dist_200ma, z_dist_200ma * 0.5), index=df.index)

        Blend_Top5 = (LinReg_200 + sig_rib_200 + Smooth_Donchian + Asym_ZDist + Dual_Mom) / 5

        L2_Dual_Mom_Cube = Dual_Mom ** 3
        L2_Blend_LinReg_Rib_m10_DoW = np.where(df.index.dayofweek == 4, Blend_m10 * 0.8, Blend_m10)
        L2_Blend_LinReg_Rib_p10_Squash = np.sign(Blend_p10) * np.sqrt(np.abs(Blend_p10))
        L2_Blend_Top5_Cube = Blend_Top5 ** 3

        er20 = df['Close'].diff(20).abs() / (df['Close'].diff().abs().rolling(20).sum() + 1e-8)
        L2_LinReg_200_ER_Boost = LinReg_200 * np.where(er20 > 0.3, 1.2, 0.8)

        def apply_softmax(b): return np.sign(b) * (np.exp(np.abs(b)*5) - 1) / (np.exp(5) - 1)
        def apply_tow_fade(b): return np.where((df.index.dayofweek == 1) & (df['Ret'].shift(1) > 0.01), b * 0.5, b)
        def apply_skew(b): return b * np.where(skew252 > 0, 1.1, 0.9)
        def apply_asym_exp(b): return np.where(b > 0, b**3, b**5)

        self.signals['L2_Dual_Mom_Cube_Softmax'] = np.clip(apply_softmax(L2_Dual_Mom_Cube), -1, 1)
        self.signals['L2_Blend_LinReg_Rib_m10_DoW_TOWFade'] = np.clip(apply_tow_fade(L2_Blend_LinReg_Rib_m10_DoW), -1, 1)
        self.signals['L2_LinReg_200_ER_Boost_Softmax'] = np.clip(apply_softmax(L2_LinReg_200_ER_Boost), -1, 1)
        self.signals['L2_Blend_LinReg_Rib_p10_Squash_TOWFade'] = np.clip(apply_tow_fade(L2_Blend_LinReg_Rib_p10_Squash), -1, 1)
        self.signals['L2_Blend_LinReg_Rib_m10_DoW_Skew'] = np.clip(apply_skew(L2_Blend_LinReg_Rib_m10_DoW), -1, 1)
        self.signals['L2_Blend_LinReg_Rib_p10_Squash_Skew'] = np.clip(apply_skew(L2_Blend_LinReg_Rib_p10_Squash), -1, 1)
        self.signals['L2_LinReg_200_ER_Boost_AsymExp'] = np.clip(apply_asym_exp(L2_LinReg_200_ER_Boost), -1, 1)
        self.signals['L2_Blend_Top5_Cube_Softmax'] = np.clip(apply_softmax(L2_Blend_Top5_Cube), -1, 1)
        self.signals['L2_LinReg_200_ER_Boost_Skew'] = np.clip(apply_skew(L2_LinReg_200_ER_Boost), -1, 1)
        self.signals['L2_LinReg_200_ER_Boost_TOWFade'] = np.clip(apply_tow_fade(L2_LinReg_200_ER_Boost), -1, 1)


class MediumTermTrendSignals(BaseSignalFamily):
    def generate_signals(self):
        c, h, l, v = self.df['Close'], self.df['High'], self.df['Low'], self.df['Volume']
        ret = c.pct_change()
        self.df['Ret'] = ret

        vol20 = ret.rolling(20).std() * np.sqrt(252)
        vol60 = ret.rolling(60).std() * np.sqrt(252)
        vol120 = ret.rolling(120).std() * np.sqrt(252)
        vol_of_vol_20 = ret.rolling(20).std().rolling(20).std()

        tr = pd.DataFrame({'hl': h-l, 'hc': (h-c.shift()).abs(), 'lc': (l-c.shift()).abs()}).max(axis=1)
        drawdown_14 = (c - c.rolling(14).max()) / c.rolling(14).max()
        ulcer_14 = np.sqrt((drawdown_14**2).rolling(14).mean()) * 100

        macd = c.ewm(span=12).mean() - c.ewm(span=26).mean()
        macd_hist = macd - macd.ewm(span=9).mean()

        autocorr20 = ret.rolling(20).apply(lambda x: pd.Series(x).autocorr(1) if len(x)>5 else 0, raw=True)
        kurt20 = ret.rolling(20).kurt()

        def calc_density(w): return (h.rolling(w).max() - l.rolling(w).min()) / (tr.rolling(w).sum() + 1e-5)
        def scale_final(s):
            s_std = s.rolling(252, min_periods=40).std().replace(0, np.nan).ffill().bfill()
            return np.tanh(s / s_std).fillna(0)

        raw1 = c.shift(27).pct_change(27) - c.pct_change(27)
        sig1 = raw1 * (ret.rolling(20).std() > ret.rolling(60).std()).astype(float)
        self.signals['Trend_Decel_55_VolBreakout_VolOfVol'] = scale_final(sig1 / (vol_of_vol_20 + 1e-5))

        raw2 = c.shift(30).pct_change(30) - c.pct_change(30)
        self.signals['Trend_Decel_60_VolBreakout_LongOnly'] = scale_final(raw2 * (vol20 > vol60).astype(float)).clip(0, 1)

        raw3 = -np.sign(c.pct_change(40)) * -c.pct_change(10)
        scaled3 = scale_final(np.sign(raw3) * (np.abs(raw3)**2))
        self.signals['Trend_Breakdown_40_SignPower_Lagged'] = 0.7 * scaled3 + 0.3 * scaled3.shift(5).fillna(0)

        raw4 = c.pct_change(25) * (1 - (ret.rolling(25).std()*np.sqrt(252) / vol120))
        self.signals['LowVol_Trend_25_SigMom_LongOnly'] = scale_final(raw4 + raw4.diff(3).fillna(0)).clip(0, 1)

        raw5 = pd.Series(np.where(ret.rolling(55).std()*np.sqrt(252) < vol120, c.pct_change(55), 0), index=c.index)
        self.signals['Consol_Breakout_55_MACDAlign_Ulcer'] = scale_final((raw5 * (np.sign(raw5) == np.sign(macd_hist)).astype(float)) / (ulcer_14 + 1))

        raw6 = -np.sign(c.pct_change(55)) * -c.pct_change(13)
        self.signals['Trend_Breakdown_55_EMASmooth_AutoCorr'] = scale_final(raw6.ewm(span=3).mean() * np.where(autocorr20 < 0, 0.5, 1.2))

        raw7 = -np.sign(c.pct_change(50)) * -c.pct_change(12)
        dens7 = calc_density(20)
        self.signals['Trend_Breakdown_50_KurtFilter_PriceDens'] = scale_final((raw7 * (kurt20 < 5.0).astype(float)) * (dens7 > dens7.rolling(252).median()).astype(float))

        raw8 = -np.sign(c.pct_change(35)) * -c.pct_change(8)
        self.signals['Trend_Breakdown_35_MedianFilter_LongBias'] = scale_final(raw8.rolling(3).median()) + 0.2

        raw9 = pd.Series(np.where(vol20 < vol120, c.pct_change(20), 0), index=c.index)
        self.signals['Consol_Breakout_20_MACDAlign_LongBias'] = scale_final(raw9 * (np.sign(raw9) == np.sign(macd_hist)).astype(float)) + 0.2


class ShortTermTrendSignals(BaseSignalFamily):
    def generate_signals(self):
        df = self.df
        df['Return'] = df['Close'].pct_change()
        ret1 = df['Return']

        ret2 = df['Close'].pct_change(2)
        ret5 = df['Close'].pct_change(5)
        ret10 = df['Close'].pct_change(10)
        ret20 = df['Close'].pct_change(20)

        vol20 = df['Return'].rolling(20).std() * np.sqrt(252)
        scaler = (0.15 / (vol20 + 1e-6)).clip(0, 2.0)

        z10 = (df['Close'] - df['Close'].rolling(10).mean()) / (df['Close'].rolling(10).std() + 1e-6)
        accel = ret5 - ret20
        macd = df['Close'].ewm(span=5).mean() - df['Close'].ewm(span=10).mean()

        obv = (np.sign(df['Return']) * df['Volume']).rolling(10).sum()
        gap_pct = df['Open'] / df['Close'].shift(1) - 1
        gap_down = df['Open'] < df['Low'].shift(1)
        roll_skew = df['Return'].rolling(60).skew()
        roll_kurt = df['Return'].rolling(60).kurt()
        down_dev = df['Return'].clip(upper=0).rolling(60).std()
        up_dev = df['Return'].clip(lower=0).rolling(60).std()
        high_vol_regime = vol20 > vol20.rolling(252).median()

        up = df['Return'].clip(lower=0)
        dn = -1 * df['Return'].clip(upper=0)
        rsi14 = 100 - (100 / (1 + up.ewm(com=13).mean() / (dn.ewm(com=13).mean() + 1e-6)))

        def linreg_r2(x):
            n = len(x)
            return scipy.stats.linregress(np.arange(n), x)[2]**2 if n >= 3 else 0
        r2_10 = df['Close'].rolling(10).apply(linreg_r2).fillna(0)

        z_sym = np.where((z10 > 0) & (z10 < 1.0) & (ret1 < 0), 1, np.where((z10 < 0) & (z10 > -1.0) & (ret1 > 0), -1, 0)) * scaler
        z_asym = np.where((z10 > 0) & (z10 < 1.0) & (ret1 < 0), 1, np.where((z10 < 0) & (z10 > -1.0) & (ret1 > 0), -0.5, 0)) * scaler
        t_sym = np.where((ret10 > 0) & (ret2 < 0), 1, np.where((ret10 < 0) & (ret2 > 0), -1, 0)) * scaler
        t_asym = np.where((ret10 > 0) & (ret2 < 0), 1, np.where((ret10 < 0) & (ret2 > 0), -0.5, 0)) * scaler
        a_pb = np.where((accel > 0) & (ret1 < 0), 1, np.where((accel < 0) & (ret1 > 0), -1, 0)) * scaler
        z_long = np.where((z10 > 0) & (z10 < 1.0) & (ret1 < 0), 1, 0) * scaler
        macd_pb = np.where((macd > 0) & (ret2 < 0), 1, np.where((macd < 0) & (ret2 > 0), -1, 0)) * scaler
        z_cont = np.where((z10 > 0) & (z10 < 1.0) & (ret1 < 0), 1 - 2*np.abs(z10 - 0.5), np.where((z10 < 0) & (z10 > -1.0) & (ret1 > 0), -1 + 2*np.abs(z10 + 0.5), 0)) * scaler

        self.signals['Composite_Z10_Trend10_GapDown_ConvictionScale'] = np.where(gap_down, np.clip(z_sym + t_sym, -1, 1), 0) * r2_10
        self.signals['Trend10_PB2_GapDown_ConvictionScale'] = np.where(gap_down, t_sym, 0) * r2_10
        self.signals['Trend10_PB2_Asym_GapDown_ConvictionScale'] = np.where(gap_down, t_asym, 0) * r2_10
        self.signals['Z10_PB_LongOnly_Distribution_LowSkew'] = np.where(roll_skew < 0, np.where(obv < 0, z_long, 0), 0)
        self.signals['MACD_PB_GapDown_LowKurtosis'] = np.where(roll_kurt < 3, np.where(gap_down, macd_pb, 0), 0)
        self.signals['Smart_Trend_Alpha_RSINeutral_GapDownMicro'] = np.where((gap_pct < 0) & (gap_pct > -0.005), np.where((rsi14 >= 30) & (rsi14 <= 70), np.clip(z_asym + t_asym + a_pb, -1, 1), 0), 0)
        self.signals['Z10_PB_Continuous_GapDown_DownsideDevHigh'] = np.where(down_dev > up_dev, np.where(gap_down, z_cont, 0), 0)
        self.signals['Trend_Accel_PB_HighVolRegime_GapDownMicro'] = np.where((gap_pct < 0) & (gap_pct > -0.005), np.where(high_vol_regime, a_pb, 0), 0)


class VolumeSignals(BaseSignalFamily):
    def generate_signals(self):
        df = self.df
        df['Ret'] = df['Close'].pct_change()
        df['H_L'] = df['High'] - df['Low']
        df['TR'] = np.maximum(df['H_L'], np.maximum(abs(df['High'] - df['Close'].shift()), abs(df['Low'] - df['Close'].shift())))
        df['Ann_Vol'] = df['Ret'].rolling(20).std() * np.sqrt(252)

        def scale_cap(sig, target_vol=0.15):
            inv_vol = target_vol / df['Ann_Vol'].replace(0, np.nan)
            return (sig * inv_vol.fillna(1).clip(0.1, 2.0)).clip(-1, 1)

        ivi = ((2*df['Close'] - df['High'] - df['Low']) / df['H_L'].replace(0, np.nan)) * df['Volume']
        hv_s = df['Ret'].rolling(10).std()
        hv_l = df['Ret'].rolling(100).std()
        atr = df['TR'].rolling(14).mean()
        vwap = (df['Close'] * df['Volume']).rolling(10).sum() / df['Volume'].rolling(10).sum()
        mfv = ((df['Close'] - df['Low']) - (df['High'] - df['Close'])) / df['H_L'].replace(0, np.nan) * df['Volume']
        chop = 100 * np.log10(df['TR'].rolling(14).sum() / (df['High'].rolling(14).max() - df['Low'].rolling(14).min())) / np.log10(14)
        vpt = (df['Ret'] * df['Volume']).cumsum()
        vma = df['Volume'].rolling(20).mean()

        sig2 = np.sign(ivi.rolling(40).mean())
        sig2 = np.where(df['Ret'].rolling(5).sum() > 0.02, 0, sig2)
        self.signals['S2_IVI'] = scale_cap(pd.Series(np.where(hv_s < hv_l, sig2, sig2 * 0.5), index=df.index))

        sig3 = np.sign(vpt.rolling(10).mean() - vpt.rolling(55).mean())
        sig3 = np.where(df['TR'] > atr, sig3, sig3 * 0.5)
        self.signals['S3_VPT'] = scale_cap(pd.Series(np.where((df['Close'] > vwap) & (sig3 < 0), 0, sig3), index=df.index))

        cmf40 = mfv.rolling(40).sum() / df['Volume'].rolling(40).sum()
        sig4 = np.tanh(cmf40 * 5)
        sig4 = np.where(df['TR'] > atr, sig4, sig4 * 0.5)
        self.signals['S4_CMF40'] = scale_cap(pd.Series(np.where(chop > 61.0, sig4, sig4 * 0.5), index=df.index))

        vw1 = (df['Close'] * df['Volume']).rolling(10).sum() / df['Volume'].rolling(10).sum()
        vw2 = (df['Close'] * df['Volume']).rolling(50).sum() / df['Volume'].rolling(50).sum()
        sig5 = np.sign(vw1 - vw2)
        sig5 = np.where(df['TR'] > atr, sig5, sig5 * 0.5)
        self.signals['S5_VWAP'] = scale_cap(pd.Series(np.where(chop > 61.0, sig5, sig5 * 0.5), index=df.index))

        sig6 = np.sign(ivi.rolling(50).mean())
        sig6 = np.where(df['TR'] > atr, sig6, sig6 * 0.5)
        self.signals['S6_IVI50'] = scale_cap(pd.Series(np.where(chop > 61.0, sig6, sig6 * 0.5), index=df.index))

        cmf50 = mfv.rolling(50).sum() / df['Volume'].rolling(50).sum()
        sig7 = np.tanh(cmf50 * 5)
        sig7 = np.where(df['TR'] > atr, sig7, sig7 * 0.5)
        self.signals['S7_CMF50'] = scale_cap(pd.Series(np.where((df['Close'] > vwap) & (sig7 < 0), 0, sig7), index=df.index))

        sig9 = np.sign(ivi.cumsum().diff(20))
        sig9 = np.where(df['TR'] > atr, sig9, sig9 * 0.5) * 0.5
        self.signals['S9_ADLMom'] = scale_cap(pd.Series(sig9, index=df.index))

        sig10 = np.sign(df['Ret'].rolling(50).sum()) * (df['Volume'] / vma)
        sig10 = np.where(df['TR'] > atr, sig10, sig10 * 0.5)
        self.signals['S10_VWM50'] = scale_cap(pd.Series(np.where(hv_s > hv_l, sig10, sig10 * 0.5), index=df.index))


class SeasonalitySignals(BaseSignalFamily):
    def generate_signals(self):
        df = self.df
        df['Ret'] = df['Close'].pct_change()

        df['Day'] = df.index.day
        df['Month'] = df.index.month
        df['DayOfWeek'] = df.index.dayofweek
        df['DaysInMonth'] = df.index.days_in_month
        df['DaysToMonthEnd'] = df['DaysInMonth'] - df['Day']

        cal = USFederalHolidayCalendar()
        holidays = cal.holidays(start=df.index.min(), end=df.index.max())
        df['PreHoliday'] = df.index.to_series().shift(1, freq='B').isin(holidays)

        df['SMA10'] = df['Close'].rolling(10).mean()
        df['SMA200'] = df['Close'].rolling(200).mean()
        df['Ret1'] = df['Close'].pct_change(1)
        df['Ret5'] = df['Close'].pct_change(5)
        df['Vol20'] = df['Ret'].rolling(20).std() * np.sqrt(252)

        df['Gap'] = df['Open'] - df['Close'].shift(1)
        df['TR'] = np.maximum(df['High'] - df['Low'], np.maximum(abs(df['High'] - df['Close'].shift(1)), abs(df['Low'] - df['Close'].shift(1))))
        df['ATR'] = df['TR'].rolling(14).mean()

        delta = df['Close'].diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
        df['RSI14'] = 100 - (100 / (1 + gain / (loss + 1e-8)))

        df['MACD'] = df['Close'].ewm(span=12).mean() - df['Close'].ewm(span=26).mean()
        df['MACD_Hist'] = df['MACD'] - df['MACD'].ewm(span=9).mean()

        df['Donchian_Width'] = df['High'].rolling(20).max() - df['Low'].rolling(20).min()
        df['Donchian_SMA50'] = df['Donchian_Width'].rolling(50).mean()

        df['VIX_P_252'] = df['ATR'] / df['Close']
        df['VIX_P_252_90'] = df['VIX_P_252'].rolling(252).quantile(0.9)
        df['VIX_P_252_20'] = df['VIX_P_252'].rolling(252).quantile(0.2)

        tom = (df['DaysToMonthEnd'] <= 3) | (df['Day'] <= 3)
        santa = ((df['Month'] == 12) & (df['Day'] >= 20)) | ((df['Month'] == 1) & (df['Day'] <= 15))
        q1q4 = df['Month'].isin([1,2,3,10,11,12])
        tom_trend = tom & (df['Close'] > df['SMA200'])
        master_base = santa | tom_trend | ((df['DayOfWeek'] == 3) & (df['Close'] > df['SMA200']))

        self.signals['B01_ToM_GapDown_M39_VIX_Panic'] = (tom & (df['Gap'] <= 0) & (df['VIX_P_252'] > df['VIX_P_252_90'])).astype(float)
        self.signals['B02_TrendToM_GapDown_M40_VIX_Complacency'] = (tom_trend & (df['Gap'] <= 0) & (df['VIX_P_252'] < df['VIX_P_252_20'])).astype(float)
        self.signals['B04_Combined_Mom5Neg_M50_Inside_Day_ATR'] = (master_base & (df['Ret5'] <= 0) & ((df['High'] - df['Low']) < df['ATR'])).astype(float)
        self.signals['B05_Q1Q4_DistLT5_M50_Inside_Day_ATR'] = (q1q4 & (((df['Close'] / df['SMA200']) - 1) < 0.05) & ((df['High'] - df['Low']) < df['ATR'])).astype(float)
        self.signals['B06_TrendSanta_RSIBear_M43_Micro_Trend_Up'] = (santa & (df['Close'] > df['SMA200']) & (df['RSI14'] < 60) & (df['Close'] > df['SMA10'])).astype(float)
        self.signals['B08_TrendWed_Ret1Neg_M45_MACD_Bullish'] = ((df['DayOfWeek'] == 1) & (df['Close'] > df['SMA200']) & (df['Ret1'] <= 0) & (df['MACD_Hist'] > 0)).astype(float)
        self.signals['B09_TrendQ1Q4_VolContract_M36_Vol_Contract_Donchian'] = (q1q4 & (df['Close'] > df['SMA200']) & (df['Vol20'] <= df['Vol20'].shift(5)) & (df['Donchian_Width'] <= df['Donchian_SMA50'])).astype(float)


class ShortOnlySignals(BaseSignalFamily):
    def generate_signals(self):
        df = self.df
        df['Ret'] = df['Close'].pct_change()

        df['Upper_Shadow'] = (df['High'] - df[['Open', 'Close']].max(axis=1)) / df['Open']
        df['Gap'] = (df['Open'] - df['Close'].shift(1)) / df['Close'].shift(1)
        df['Intraday'] = (df['Close'] - df['Open']) / df['Open']

        df['SMA20'] = df['Close'].rolling(20).mean()
        df['Vol20'] = df['Volume'].rolling(20).mean()
        df['High_to_Low'] = (df['High'] - df['Low']) / df['Low']
        df['ATR14'] = df['High_to_Low'].rolling(14).mean()
        df['Parkinson'] = np.sqrt((1 / (4 * np.log(2))) * (np.log(df['High'] / df['Low']))**2).rolling(20).mean()

        delta = df['Close'].diff()
        rs = delta.clip(lower=0).ewm(com=13, adjust=False).mean() / (-delta.clip(upper=0).ewm(com=13, adjust=False).mean() + 1e-8)
        df['RSI14'] = 100 - (100 / (1 + rs))

        df['BB_mid'] = df['Close'].rolling(20).mean()
        df['BB_std'] = df['Close'].rolling(20).std()
        df['BB_width'] = (df['BB_mid'] + 2 * df['BB_std'] - (df['BB_mid'] - 2 * df['BB_std'])) / df['BB_mid']
        df['Z_Close'] = (df['Close'] - df['SMA20']) / (df['BB_std'] + 1e-8)

        df['High20'] = df['High'].rolling(20).max()
        df['Low20'] = df['Low'].rolling(20).min()
        df['Donchian_L'] = df['Low'].rolling(20).min()
        df['Close_Near_20L'] = (df['Close'] - df['Low20']) / (df['High20'] - df['Low20'] + 1e-8)

        up_days = (df['Ret'] > 0).astype(int)
        df['Cons_Up'] = up_days.groupby((up_days != up_days.shift()).cumsum()).cumsum()
        df['Ret5'] = df['Close'].pct_change(5)
        df['Ret10'] = df['Close'].pct_change(10)

        df['CHOP'] = 100 * np.log10((df['High'] - df['Low']).rolling(14).sum() / (df['High'].rolling(14).max() - df['Low'].rolling(14).min() + 1e-8)) / np.log10(14)
        df['Skew'] = df['Ret'].rolling(20).skew()
        typical_price = (df['High'] + df['Low'] + df['Close']) / 3
        df['VWAP_20'] = (typical_price * df['Volume']).rolling(20).sum() / df['Volume'].rolling(20).sum()
        df['Vol_Rank'] = df['Volume'].rolling(100).rank(pct=True)

        self.signals['Drawdown_Accel'] = np.where((df['Ret10'] < -0.01) & (df['Ret'] < -0.01) & (df['Volume'] > df['Vol20'] * 1.5) & (df['Close_Near_20L'] < 0.2), -1, 0)
        self.signals['ConsUp5_Exhaust'] = np.where((df['Cons_Up'] >= 5) & (df['Ret5'] > 0.02) & (df['Close'] > df['High'] - 0.3 * (df['High'] - df['Low'])) & (df['Open'] > df['Close'].shift(1)), -1, 0)
        self.signals['VolaSq_VolRank'] = np.where((df['BB_width'] < 0.04) & (df['Z_Close'] < -1.0) & (df['Volume'] > df['Vol20'] * 1.5) & (df['Vol_Rank'] > 0.75), -1, 0)
        self.signals['Trend_Exhaust_Gap'] = np.where((df['Ret5'] > 0.05) & (df['Upper_Shadow'] > 0.002) & (df['ATR14'] > df['ATR14'].rolling(50).mean()) & (df['Open'] > df['Close'].shift(1)), -1, 0)
        self.signals['Gap_Down_VWAP'] = np.where((df['Gap'] < -0.015) & (df['Volume'] > df['Vol20'] * 1.5) & (df['Close'] < df['VWAP_20']), -1, 0)
        self.signals['ConsUp2_Parkinson'] = np.where((df['Cons_Up'] >= 2) & (df['Ret5'] > 0.02) & (df['Gap'] < 0) & (df['Parkinson'] > df['Parkinson'].rolling(50).mean()), -1, 0)
        self.signals['VolaSq_Donchian'] = np.where((df['BB_width'] < 0.03) & (df['Z_Close'] < -1.0) & (df['Close'] > df['High'] - 0.3 * (df['High'] - df['Low'])) & (df['Low'] <= df['Donchian_L']), -1, 0)
        self.signals['Gap_Up_Fade'] = np.where((df['Gap'] > 0.005) & (df['Intraday'] < -0.01) & (df['Volume'] > df['Vol20'] * 1.5) & (df['Skew'] < -0.5), -1, 0)
        self.signals['ConsUp3_Trending'] = np.where((df['Cons_Up'] >= 3) & (df['Ret5'] > 0.02) & (df['RSI14'] >= 40) & (df['RSI14'] <= 60) & (df['CHOP'] < 40), -1, 0)


class AsymmetricVolatilitySignals(BaseSignalFamily):
    def generate_signals(self):
        df = self.df
        df['ret'] = df['Close'].pct_change()
        df['pos_ret'] = df['ret'].clip(lower=0)
        df['neg_ret'] = df['ret'].clip(upper=0)

        def zsc(x, w=252): return (x - x.rolling(w, min_periods=w//2).mean()) / (x.rolling(w, min_periods=w//2).std() + 1e-9)
        def norm(x): return np.tanh(zsc(x, 252))

        # Re-creating formulas logically to avoid eval() namespace issues internally
        # 1. Up_Dn_Vol_Ratio_4_Inv_sm3_High_Vol_Regime_Flash_Crash_Proxy
        raw1 = -norm((df['pos_ret'].rolling(4).std() / (df['neg_ret'].rolling(4).std() + 1e-9)) - 1).rolling(3, min_periods=1).mean()
        raw1 *= np.where(df['ret'].rolling(20).std() > df['ret'].rolling(20).std().rolling(100).mean(), 1, 0)
        raw1 *= np.where((df['ret'] < -0.02) & (df['Volume'] > df['Volume'].rolling(20).mean() * 1.5), 0, 1)
        self.signals['Up_Dn_Vol_Ratio_4_Inv_sm3_High_Vol_Regime_Flash_Crash_Proxy'] = raw1

        # 2. Asym_Vol_Corr_Combo_Avoid_Oversold_ATR_Vol_Scale
        raw2 = norm(zsc(df['pos_ret'].rolling(20).std() - df['neg_ret'].rolling(20).std(), 60) + norm(df['ret'].rolling(10).corr(df['ret'].rolling(10).std())))
        rsi = 100 - (100 / (1 + (df['Close'].diff().where(df['Close'].diff() > 0, 0).rolling(14).mean() / (-df['Close'].diff().where(df['Close'].diff() < 0, 0).rolling(14).mean() + 1e-9))))
        raw2 *= np.where(rsi < 30, 0, 1)
        raw2 *= np.where((df['High']-df['Low']) > (df['High']-df['Low']).rolling(50).mean(), 1.5, 0.5)
        self.signals['Asym_Vol_Corr_Combo_Avoid_Oversold_ATR_Vol_Scale'] = raw2

        # 3. EWMA_Vol_Asym_10_5D_Trend_Filter_ATR_Vol_Scale
        raw3 = norm((df['pos_ret'].ewm(span=10).std() - df['neg_ret'].ewm(span=10).std()) / (df['pos_ret'].ewm(span=10).std() + df['neg_ret'].ewm(span=10).std() + 1e-9))
        raw3 *= np.where(df['Close'].pct_change(5) > 0, 1, 0)
        raw3 *= np.where((df['High']-df['Low']) > (df['High']-df['Low']).rolling(50).mean(), 1.5, 0.5)
        self.signals['EWMA_Vol_Asym_10_5D_Trend_Filter_ATR_Vol_Scale'] = raw3

        # 4. Semi_Vol_Z_Spread_Avoid_Oversold_Wide_Range
        raw4 = norm(zsc(df['pos_ret'].rolling(20).std(), 60) - zsc(df['neg_ret'].rolling(20).std(), 60))
        raw4 *= np.where(rsi < 30, 0, 1)
        raw4 *= np.where((df['High'] - df['Low']) > (df['High'] - df['Low']).rolling(20).mean() * 1.5, 1.5, 0.5)
        self.signals['Semi_Vol_Z_Spread_Avoid_Oversold_Wide_Range'] = raw4


class FibonacciSignals(BaseSignalFamily):
    def generate_signals(self):
        df = self.df
        Close, Open, High, Low, Volume = df['Close'], df['Open'], df['High'], df['Low'], df['Volume']
        ret = Close.pct_change().fillna(0)
        df['Ret'] = ret

        SMA50 = Close.rolling(50).mean()
        TR = np.maximum(High - Low, np.maximum(abs(High - Close.shift(1)), abs(Low - Close.shift(1))))
        ATR21 = TR.rolling(21).mean()
        VolSMA21 = Volume.rolling(21).mean()

        gap = abs(Open - Close.shift(1))
        skew21 = ret.rolling(21).skew().fillna(0)
        mom21 = np.sign(Close - Close.shift(21))
        AutoCorr = ret.rolling(21).corr(ret.shift(1)).fillna(0)

        delta = Close.diff()
        rs = delta.clip(lower=0).ewm(com=13, adjust=False).mean() / (-delta.clip(upper=0).ewm(com=13, adjust=False).mean() + 1e-8)
        RSI14 = 100 - (100 / (1 + rs))

        BB_mid = Close.rolling(20).mean()
        BB_std = Close.rolling(20).std()
        BBW = (BB_mid + 2*BB_std - (BB_mid - 2*BB_std)) / (BB_mid + 1e-8)
        BBW_MA = BBW.rolling(20).mean()

        H14, L14 = High.rolling(14).max(), Low.rolling(14).min()
        CHOP = 100 * np.log10(TR.rolling(14).sum() / (H14 - L14 + 1e-8)) / np.log10(14)

        VM_plus = abs(High - Low.shift(1))
        VM_minus = abs(Low - High.shift(1))
        VI_plus = VM_plus.rolling(14).sum() / (TR.rolling(14).sum() + 1e-8)
        VI_minus = VM_minus.rolling(14).sum() / (TR.rolling(14).sum() + 1e-8)

        Keltner_Lower = Close.ewm(span=20).mean() - 2 * TR.rolling(20).mean()

        def get_fib(n):
            H = High.rolling(n).max()
            L = Low.rolling(n).min()
            return (Close - L) / (H - L + 1e-8)

        # 10 Strongly Robust Signals (smoothed by ewm(span=5))
        self.signals['S1_MR_144_AutoCorr'] = (-(get_fib(144) - 0.786)*2 * (gap < ATR21*0.5) * (AutoCorr > 0)).ewm(span=5).mean()
        self.signals['S2_MR_89_ChopLow'] = (-(get_fib(89) - 0.786)*2 * (gap < ATR21*0.5) * (CHOP <= 50)).ewm(span=5).mean()
        self.signals['S3_MR_34_Doji'] = (-(get_fib(34) - 0.786)*2 * (skew21 > 0) * (abs(Open - Close) > (High - Low) * 0.1)).ewm(span=5).mean()

        base_s4 = -(get_fib(55) - 0.786)*2 * (RSI14 <= 50)
        self.signals['S4_MR_55_RSI_SQ'] = pd.Series(np.where(ret.rolling(5).sum() > 0.05, base_s4.clip(lower=0), base_s4), index=df.index).ewm(span=5).mean()

        self.signals['S5_Mom_55_LowVol'] = ((get_fib(55) - 0.236)*2 * (Volume <= VolSMA21) * (Close > Close.shift(3))).ewm(span=5).mean()
        self.signals['S6_Mom_144_Vortex'] = ((get_fib(144) - 0.236)*2 * (np.sign((get_fib(144) - 0.236)*2) != mom21) * (VI_plus <= VI_minus)).ewm(span=5).mean()
        self.signals['S7_Mom_89_BBVol'] = ((get_fib(89) - 0.236)*2 * (BBW >= BBW_MA) * (Volume > Volume.shift(1) * 2)).ewm(span=5).mean()
        self.signals['S8_Mom_233_Keltner'] = ((get_fib(233) - 0.236)*2 * (np.sign((get_fib(233) - 0.236)*2) != mom21) * (Close < Keltner_Lower)).ewm(span=5).mean()
        self.signals['S9_Mom_34_EndMo'] = ((get_fib(34) - 0.236)*2 * (Close > SMA50) * (df.index.day >= 20)).ewm(span=5).mean()
        self.signals['S10_Mom_13_Vortex'] = ((get_fib(13) - 0.236)*2 * (np.sign((get_fib(13) - 0.236)*2) != mom21) * (VI_plus <= VI_minus)).ewm(span=5).mean()


class VolatilityMomentumSignals(BaseSignalFamily):
    def generate_signals(self):
        df = self.df
        vix = self.vix
        vvix = self.vvix

        if vix is None or vvix is None:
            return

        df['VIX'] = vix['Close']
        df['VVIX'] = vvix['Close']
        df['VIX_High'] = vix['High']
        df['VIX_Low'] = vix['Low']
        df['GLD'] = df['Close']

        df['Ret'] = df['Close'].pct_change()
        df['GLD_ROC1'] = df['Ret']
        df['VIX_ROC1'] = df['VIX'].pct_change(1)
        df['VVIX_ROC1'] = df['VVIX'].pct_change(1)

        df['VIX_ROC3'] = df['VIX'].pct_change(3)
        df['VIX_ROC5'] = df['VIX'].pct_change(5)

        df['VIX_MA20'] = df['VIX'].rolling(20).mean()
        df['VIX_MA60'] = df['VIX'].rolling(60).mean()
        df['VIX_MA100'] = df['VIX'].rolling(100).mean()
        df['VVIX_MA20'] = df['VVIX'].rolling(20).mean()
        df['VVIX_MA60'] = df['VVIX'].rolling(60).mean()

        df['VIX_STD20'] = df['VIX'].rolling(20).std()
        df['VIX_Z20'] = (df['VIX'] - df['VIX_MA20']) / df['VIX_STD20']
        df['VVIX_Z20'] = (df['VVIX'] - df['VVIX_MA20']) / df['VVIX'].rolling(20).std()

        df['GLD_Vol'] = df['GLD_ROC1'].rolling(20).std() * np.sqrt(252)
        df['VVIX_HV10'] = df['VVIX_ROC1'].rolling(10).std() * np.sqrt(252)
        df['VVIX_HV50'] = df['VVIX_ROC1'].rolling(50).std() * np.sqrt(252)
        df['VIX_HV10'] = df['VIX_ROC1'].rolling(10).std() * np.sqrt(252)
        df['VIX_HV50'] = df['VIX_ROC1'].rolling(50).std() * np.sqrt(252)

        df['VIX_VVIX_Ratio'] = df['VIX'] / df['VVIX']
        df['VIX_VVIX_Ratio_Z20'] = (df['VIX_VVIX_Ratio'] - df['VIX_VVIX_Ratio'].rolling(20).mean()) / df['VIX_VVIX_Ratio'].rolling(20).std()
        df['VIX_Close_Pos'] = (df['VIX'] - df['VIX_Low']) / (df['VIX_High'] - df['VIX_Low'] + 1e-8)

        rs = df['Close'].diff().clip(lower=0).ewm(com=13, adjust=False).mean() / (-df['Close'].diff().clip(upper=0).ewm(com=13, adjust=False).mean() + 1e-8)
        df['GLD_RSI14'] = 100 - (100 / (1 + rs))

        self.signals['Exposure_1'] = np.where(((df['VIX_ROC1'] < -0.15) & (df['GLD_RSI14'] > 60)) & (df['GLD_Vol'].rolling(5).mean() > df['GLD_Vol'].rolling(20).mean()), 1, 0)
        self.signals['Exposure_2'] = np.where(((((df['VIX_Z20'] > 2.0).rolling(5).max() == 1) & (df['VIX_Z20'] < 1.2)) & (df['GLD_ROC1'] > 0)) & (df['VVIX_HV10'] > df['VVIX_HV50']), 1, 0)
        self.signals['Exposure_3'] = np.where((((df['VIX'] < 16) & (df['VIX_ROC5'] < 0)) & (df['VIX_MA20'] > df['VIX_MA60'])) & (df['VVIX_ROC1'].rolling(10).skew() > 0), 1, 0)
        self.signals['Exposure_4'] = np.where(((df['VIX_ROC3'] > 0.35) & (df['GLD_ROC1'] > 0)) & ((df['VIX_High'] > df['VIX_High'].shift(1)) & (df['VIX_Low'] > df['VIX_Low'].shift(1))), -1, 0)
        self.signals['Exposure_5'] = np.where((((df['VIX_High'] > df['VIX_MA20'] + 2*df['VIX_STD20']) & (df['VIX_Close_Pos'] < 0.35)) & (df['GLD_RSI14'] > 60)) & (df['VIX_ROC1'].rolling(10).skew() > 0), 1, 0)
        self.signals['Exposure_6'] = np.where(((df['VIX_MA20'] < df['VIX_MA100']) & (df['VIX_VVIX_Ratio'].pct_change(1) > 0)) & (df['VIX_ROC1'].rolling(10).skew() > 0), 1, 0)
        self.signals['Exposure_7'] = np.where(((df['VIX_MA20'] > df['VIX_MA60']) & (df['VIX_Close_Pos'] <= 0.5)) & (df['VVIX_ROC1'].rolling(10).corr(df['GLD_ROC1']) > 0), 1, 0)
        self.signals['Exposure_8'] = np.where((((df['VIX'] / df['VVIX'] - df['VIX_VVIX_Ratio'].rolling(20).mean()) / df['VIX_VVIX_Ratio'].rolling(20).std() > 2.0) & (df['VIX_MA20'] > df['VIX_MA60'])) & (df['VIX_ROC1'].rolling(10).skew() > 0), -1, 0)
        self.signals['Exposure_9'] = np.where(((df['VIX_Z20'] > 0) & (df['VVIX_Z20'] < 0) & (df['VVIX_MA20'] > df['VVIX_MA60'])) & (df.index.day >= 24), 1, 0)
        self.signals['Exposure_10'] = np.where(((df['GLD'] == df['GLD'].rolling(20).max()) & (df['VIX'] == df['VIX'].rolling(20).max()) & (df['VIX_VVIX_Ratio'].pct_change(1) > 0)) & (df['VIX_HV10'] > df['VIX_HV50']), -1, 0)


class MarketEfficiencyNoiseSignals(BaseSignalFamily):
    def generate_signals(self):
        df = self.df
        c, o, v = df['Close'], df['Open'], df['Volume']
        ret = c.pct_change()
        df['Ret'] = ret

        def get_er(c_s, lag):
            return (c_s.diff(lag).abs() / c_s.diff().abs().rolling(lag).sum()).fillna(0)
        def get_ac(ret_s, lag):
            return ret_s.rolling(lag).apply(lambda x: pd.Series(x).autocorr(lag=1) if len(x)>1 else np.nan).fillna(0)

        # 1. Vol_Regime_UpTrend
        er = get_er(c, 10)
        vol_ma = v.rolling(20).mean()
        ma = c.rolling(200).mean()
        body = c - o
        S_raw = np.where(er > 0.3, ((v / vol_ma - 1).clip(0, 3)) * np.sign(ret), -((v / vol_ma - 1).clip(0, 3)) * np.sign(ret))
        base1 = np.where(np.sign(body) == np.sign(S_raw), S_raw, 0)
        self.signals['Vol_Regime_UpTrend'] = np.where(c > ma, np.where(base1 > 0, base1, 0), base1)

        # 2. Vol_Regime_Rev_UpTrend
        v_sh = ret.rolling(20).std()
        v_lg = ret.rolling(100).std()
        base2 = np.where(v > vol_ma, np.where(v_sh > v_lg, -np.sign(ret), np.sign(ret)), 0)
        self.signals['Vol_Regime_Rev_UpTrend'] = np.where(c > ma, np.where(base2 > 0, base2, 0), base2)

        # 3. ER_Breakout_Drift
        ac = get_ac(ret, 10)
        drift = (o - c.shift(1)).rolling(5).sum()
        bk_up = c > c.rolling(20).max().shift(1)
        bk_dn = c < c.rolling(20).min().shift(1)
        base3 = np.where(ac > 0.1, np.where(bk_up & (er > 0.3), 1, np.where(bk_dn & (er > 0.3), -1, 0)), 0)
        self.signals['ER_Breakout_Drift'] = np.where(np.sign(drift) == np.sign(base3), base3, 0)


class AutocorrelationSignals(BaseSignalFamily):
    def generate_signals(self):
        df = self.df
        df['Ret1'] = df['Close'].pct_change()
        df['Ret'] = df['Ret1']

        df['Vol20'] = df['Ret1'].rolling(20).std()
        df['MA50'] = df['Close'].rolling(50).mean()
        df['MA200'] = df['Close'].rolling(200).mean()
        df['SqRet'] = df['Ret1']**2
        df['SqRet_EMA20'] = df['SqRet'].ewm(span=20).mean()
        df['InsideDay'] = (df['High'] < df['High'].shift(1)) & (df['Low'] > df['Low'].shift(1))
        df['Ret5'] = df['Close'].pct_change(5)

        dir_20 = df['Close'].diff(20).abs()
        vol_sum_20 = df['Close'].diff().abs().rolling(20).sum()
        df['ER20'] = dir_20 / (vol_sum_20 + 1e-8)

        # 1. Contrarian Trap-Door
        self.signals['Contrarian_Trap_Door'] = (np.where(df['Ret1'] < 0, df['Ret1'].abs() / df['Vol20'], 0)) * \
                 (np.where(df['Close'] <= df['MA200'], 1, 0)) * \
                 (np.where(df['SqRet'] > df['SqRet_EMA20'], 1, 0))

        # 2. Efficient Pullback
        trend_cond = np.where((df['MA50'] > df['MA200']) & (df['Ret1'] < 0), 1, np.where((df['MA50'] < df['MA200']) & (df['Ret1'] > 0), -1, 0))
        self.signals['Efficient_Pullback'] = trend_cond * (np.where(df['Ret5'] <= 0, 1, 0)) * (np.where(df['ER20'] > 0.3, 1, 0))

        # 3. Silent Breakout
        self.signals['Silent_Breakout'] = (df['Ret1'].shift(1).fillna(0)) * (np.where(df['InsideDay'], 1, 0)) * (np.where(df['SqRet'] <= df['SqRet_EMA20'], 1, 0))


class ReturnCorrelationSignals(BaseSignalFamily):
    def generate_signals(self):
        df = self.df
        df['Ret'] = df['Close'].pct_change()
        df['ID_Ret'] = df['Close'] / df['Open'] - 1

        w, pct, cap, smooth = 40, 0.7, 0.022, 6
        ret_sum = df['Ret'].rolling(w).sum()
        id_sum = df['ID_Ret'].rolling(w).sum()
        ret_max = df['Ret'].rolling(w).max()
        base_cond_s8 = (ret_sum > 0) & (id_sum > pct * ret_sum) & (ret_max < cap)

        macd = df['Close'].ewm(span=12).mean() - df['Close'].ewm(span=26).mean()
        macd_bull = macd > macd.ewm(span=9).mean()
        inverse_vol = np.clip(0.10 / (df['Ret'].rolling(20).std() * np.sqrt(252) + 1e-5), 0, 1.5)
        self.signals['S8_MACD_Bull_Inverse_Vol'] = (base_cond_s8 & macd_bull).astype(float).rolling(smooth).mean() * inverse_vol

        base_cond_s2 = (ret_sum > 0) & (id_sum > 1.0 * ret_sum) & (ret_max < cap)
        rs = df['Close'].diff().where(df['Close'].diff() > 0, 0).rolling(14).mean() / (-df['Close'].diff().where(df['Close'].diff() < 0, 0).rolling(14).mean() + 1e-8)
        rsi_gt_40 = (100 - (100 / (1 + rs))) > 40
        donchian_bull = df['Close'] > (df['High'].rolling(20).max() + df['Low'].rolling(20).min()) / 2
        cmf = (((df['Close'] - df['Low']) - (df['High'] - df['Close'])) / (df['High'] - df['Low'] + 1e-5)) * df['Volume']
        cmf_bull = (cmf.rolling(20).sum() > 0).astype(float)
        self.signals['S2_Filter_CMF_Bull'] = (base_cond_s2 & rsi_gt_40).astype(float).rolling(smooth).mean() * donchian_bull.astype(float) * cmf_bull

        ud_vol_bull = (df['Volume'] * (df['Ret'] > 0)).rolling(50).sum() / ((df['Volume'] * (df['Ret'] < 0)).rolling(50).sum() + 1e-8) > 1.0
        tr = np.maximum(df['High'] - df['Low'], np.maximum(abs(df['High'] - df['Close'].shift(1)), abs(df['Low'] - df['Close'].shift(1))))
        inverse_atr = np.clip(0.10 / (tr.rolling(14).mean() / df['Close'] * np.sqrt(252) + 1e-5), 0, 1.5)
        self.signals['S9_Scale_Inverse_ATR'] = (base_cond_s8 & macd_bull).astype(float).rolling(5).mean() * ud_vol_bull.astype(float) * inverse_atr


class VolumeVolatilityIntersectionSignals(BaseSignalFamily):
    def generate_signals(self):
        gld = self.df
        vix = self.vix
        vvix = self.vvix

        if vix is None or vvix is None:
            return

        # Align all three datasets to a common date index
        merged = pd.concat(
            [
                gld[["Open", "Close", "Volume"]].rename(columns={
                    "Open": "GLD_Open",
                    "Close": "GLD_Close",
                    "Volume": "GLD_Volume"
                }),
                vix[["Close", "High", "Low"]].rename(columns={
                    "Close": "VIX_Close",
                    "High": "VIX_High",
                    "Low": "VIX_Low"
                }),
                vvix[["Close", "High", "Low"]].rename(columns={
                    "Close": "VVIX_Close",
                    "High": "VVIX_High",
                    "Low": "VVIX_Low"
                })
            ],
            axis=1,
            join="inner"
        ).sort_index()

        # Short aliases on the aligned index
        gld_close = merged["GLD_Close"]
        gld_open = merged["GLD_Open"]
        gld_volume = merged["GLD_Volume"]

        vix_close = merged["VIX_Close"]
        vix_high = merged["VIX_High"]
        vix_low = merged["VIX_Low"]

        vvix_close = merged["VVIX_Close"]
        vvix_high = merged["VVIX_High"]
        vvix_low = merged["VVIX_Low"]

        # Core returns
        gld_c = gld_close.pct_change()
        vix_c = vix_close.pct_change()
        vvix_c = vvix_close.pct_change()

        # Store GLD returns on the original family df if needed elsewhere
        self.df["Ret"] = self.df["Close"].pct_change()

        vix_5c = vix_c.rolling(5).sum()
        vvix_5c = vvix_c.rolling(5).sum()
        gld_10r = gld_close.pct_change(10)
        gld_20r = gld_close.pct_change(20)

        vol_z = (gld_volume - gld_volume.rolling(20).mean()) / (gld_volume.rolling(20).std() + 1e-8)
        vix_z = (vix_close - vix_close.rolling(20).mean()) / (vix_close.rolling(20).std() + 1e-8)
        vvix_z = (vvix_close - vvix_close.rolling(20).mean()) / (vvix_close.rolling(20).std() + 1e-8)
        vix_ma50 = vix_close.rolling(50).mean()
        corr_vix_vvix = vix_close.rolling(20).corr(vvix_close).fillna(0)

        # 1
        base1 = pd.Series(
            np.where((vix_c < -0.05) & (vvix_c < -0.05) & (vol_z > 0.5), 1.0, 0.0),
            index=merged.index
        )
        self.signals["1_Pure_Strong_Reversal"] = base1 * pd.Series(
            np.where((vix_close / vvix_close) > 0.15, 1.0, 0.0),
            index=merged.index
        )

        # 2
        sig_panic = pd.Series(
            np.where((vix_close > 20) & (vix_close.diff() < 0) & (vvix_close.diff() < 0), 1.0, 0.0),
            index=merged.index
        )
        sig_vol_exp = pd.Series(
            np.where((vol_z > 1) & (vix_z > 1) & (vvix_z > 1), -1.0, 0.0),
            index=merged.index
        )
        sig_div = pd.Series(
            np.where((vix_close.diff() > 0) & (vvix_close.diff() < 0) & (gld_c > 0), 1.0, 0.0),
            index=merged.index
        )
        sig_trend = pd.Series(
            np.where((gld_20r > 0) & (vix_c < -0.05), 1.0, 0.0),
            index=merged.index
        )
        raw2 = (
            1.5 * sig_panic
            + 1.0 * sig_trend
            + 1.0 * pd.Series(np.where(vvix_c < -0.05, 1, 0), index=merged.index)
            + 1.5 * sig_vol_exp
            + 1.0 * sig_div
            - 0.5 * pd.Series(np.where((vix_c > 0.1) & (vvix_c > 0.1), 1, 0), index=merged.index)
        )
        self.signals["2_Holy_Grail_1"] = np.clip(raw2, -1.0, 1.0) * pd.Series(
            np.where(corr_vix_vvix > 0, 1.0, 0.0),
            index=merged.index
        )

        # 3
        cont_hg2 = -1.5 * vvix_c - 1.5 * vix_c + 0.5 * np.sign(gld_20r)
        cont_hg2 = pd.Series(cont_hg2, index=merged.index)
        cont_hg2 = pd.Series(
            np.where((vix_close > 30) & (vix_c > 0), -1.0, cont_hg2),
            index=merged.index
        )
        cont_hg2 = pd.Series(
            np.where(sig_panic > 0, 1.0, cont_hg2),
            index=merged.index
        )
        self.signals["3_Holy_Grail_2"] = np.clip(cont_hg2, -1.0, 1.0) * pd.Series(
            np.where(vvix_5c > 0, 1.0, 0.0),
            index=merged.index
        )

        # 4
        sqz = -1.0 * vix_c - 1.0 * vvix_c
        sqz = pd.Series(sqz, index=merged.index)
        self.signals["4_Trend_Bounded_Squeeze"] = pd.Series(
            np.where(gld_10r > 0, np.clip(sqz, 0.0, 1.0), np.clip(sqz, -1.0, 0.0)),
            index=merged.index
        ) * pd.Series(
            np.where(vix_5c > 0, 1.0, 0.0),
            index=merged.index
        )

        # 5
        base6 = pd.Series(
            np.where((vix_close > 20) & (vix_close.diff() < 0), 1.0, 0.0),
            index=merged.index
        ) * pd.Series(
            np.where(vix_close > vix_ma50, 1.0, 0.0),
            index=merged.index
        )
        rng_cond = (vvix_high - vvix_low) < (vvix_high - vvix_low).rolling(20).mean()
        self.signals["5_High_VIX_Contraction"] = base6 * pd.Series(
            np.where(rng_cond, 1.0, 0.0),
            index=merged.index
        )

        # 6
        base7 = pd.Series(
            np.where((vix_c < -0.02) & (vvix_c < -0.02) & (gld_10r > 0), 1.0, 0.0),
            index=merged.index
        )
        self.signals["6_VIX_VVIX_Drop_Trend"] = base7 * pd.Series(
            np.where(corr_vix_vvix > 0, 1.0, 0.0),
            index=merged.index
        )

        # 7
        div_c = pd.Series(
            np.where(
                (vix_close.diff() > 0) & (vvix_close.diff() < 0), 1.0,
                np.where((vix_close.diff() < 0) & (vvix_close.diff() > 0), -1.0, 0.0)
            ),
            index=merged.index
        )
        super_c = 0.5 * sqz + 0.3 * div_c + 0.2 * pd.Series(
            np.where(vix_c > 0.15, -1.0, 0.0),
            index=merged.index
        )
        self.signals["7_Super_Combo_B"] = np.clip(super_c, -1.0, 1.0) * pd.Series(
            np.where(gld_open > gld_close.shift(1), 1.0, 0.0),
            index=merged.index
        )

        # 8
        regime = pd.Series(np.where(vix_close > 20, 1.5, 0.5), index=merged.index)
        base10 = np.clip(sqz * regime, -1.0, 1.0) * pd.Series(
            np.where(vix_close > vix_ma50, 1.0, 0.0),
            index=merged.index
        )
        self.signals["8_Squeeze_High_VIX"] = base10 * pd.Series(
            np.where(gld_close < gld_open, 1.0, 0.0),
            index=merged.index
        )


class HurstExponentSignals(BaseSignalFamily):
    def generate_signals(self):
        df = self.df
        df['Ret'] = df['Close'].pct_change()

        def calc_rs_hurst(prices, window):
            log_ret = np.log(prices).diff().fillna(0).values
            h_vals = np.zeros(len(log_ret))
            for i in range(window, len(log_ret)):
                x = log_ret[i-window:i]
                S = np.std(x, ddof=0)
                if S == 0:
                    h_vals[i] = 0.5
                    continue
                cum_y = np.cumsum(x - np.mean(x))
                R = np.max(cum_y) - np.min(cum_y)
                h_vals[i] = np.log(R/S) / np.log(window) if R != 0 else 0.5
            return pd.Series(h_vals, index=prices.index).replace(0, 0.5)

        h20 = calc_rs_hurst(df['Close'], 20)
        h40 = calc_rs_hurst(df['Close'], 40)
        h60 = calc_rs_hurst(df['Close'], 60)
        h120 = calc_rs_hurst(df['Close'], 120)

        diff = df['Close'].diff(1)
        rsi14 = 100 - (100 / (1 + diff.where(diff > 0, 0).rolling(14).mean() / -diff.where(diff < 0, 0).rolling(14).mean()))

        sma20 = df['Close'].rolling(20).mean()
        sma40 = df['Close'].rolling(40).mean()

        vol_ratio = df['Volume'] / df['Volume'].rolling(20).mean()
        mf_mult = ((df['Close'] - df['Low']) - (df['High'] - df['Close'])) / (df['High'] - df['Low'] + 1e-8)
        cmf = (mf_mult * df['Volume']).rolling(20).sum() / (df['Volume'].rolling(20).sum() + 1e-8)
        h_20_120_z = (h20 - h120) / h20.rolling(252).std()
        tr = np.maximum(df['High'] - df['Low'], np.maximum(abs(df['High']-df['Close'].shift()), abs(df['Low']-df['Close'].shift())))
        chop = 100 * np.log10(tr.rolling(14).sum() / (df['High'].rolling(14).max() - df['Low'].rolling(14).min() + 1e-8)) / np.log10(14)

        sig2 = pd.Series(0, index=df.index)
        sig2[(h20 < 0.45) & (rsi14 < 20)] = 1
        sig2[(h20 < 0.45) & (rsi14 > 80)] = -1
        sig2[df.index.dayofweek == 0] = 0
        sig2[(sig2 < 0) & (df['Ret'] < 0)] = 0
        self.signals['S2_HurstRSIFade'] = sig2

        sig3 = pd.Series(0, index=df.index)
        sig3[(h20 - h60) > 0.015] = np.sign(df['Close'] - sma20)
        sig3[(h20 - h60) < -0.015] = -np.sign(df['Close'] - sma20)
        sig3[sig3 < 0] *= 0.5
        sig3[(sig3 < 0) & (df['Ret'] < 0)] = 0
        self.signals['S3_HurstSlope_AsymUp'] = sig3

        sig5 = pd.Series(0, index=df.index)
        sig5[(h20 - h60) > 0.02] = np.sign(df['Close'] - sma20)
        sig5[(h20 - h60) < -0.02] = -np.sign(df['Close'] - sma20)
        sig5[sig5 < 0] *= 0.5
        sig5[sig5 < 0] *= np.clip(1 - vol_ratio, 0, 1)[sig5 < 0]
        self.signals['S5_HurstSlope_VolScale'] = sig5

        sig6 = pd.Series(0, index=df.index)
        sig6[(h40 - h60) > 0.04] = np.sign(df['Close'] - sma20)
        sig6[(h40 - h60) < -0.04] = -np.sign(df['Close'] - sma20)
        sig6[df.index.dayofweek == 0] = 0
        sig6[h_20_120_z > 2.0] = -sig6[h_20_120_z > 2.0]
        self.signals['S6_HurstSlope_InvZ'] = sig6

        sig7 = pd.Series(0, index=df.index)
        sig7[(h40 - h120) > 0.05] = np.sign(df['Close'] - sma40)
        sig7[(h40 - h120) < -0.05] = -np.sign(df['Close'] - sma40)
        sig7[np.log(df['Close']).diff().rolling(20).std() > np.log(df['Close']).diff().rolling(120).std()] = 0
        sig7[chop < 40] = 0
        self.signals['S7_HurstSlope_VolSq'] = sig7

        sig9 = pd.Series(0, index=df.index)
        sig9[(h20 - h60) > 0.03] = np.sign(df['Close'] - sma20)
        sig9[(h20 - h60) < -0.03] = -np.sign(df['Close'] - sma20)
        sig9[sig9 < 0] *= 0.5
        sig9[(sig9 > 0) & (cmf < 0)] = 0
        sig9[(sig9 < 0) & (cmf > 0)] = 0
        self.signals['S9_HurstSlope_CMF'] = sig9

        sig10 = pd.Series(0, index=df.index)
        sig10[(h20 - h120) > 0.02] = np.sign(df['Close'] - sma20)
        sig10[(h20 - h120) < -0.02] = -np.sign(df['Close'] - sma20)
        sig10[(sig10 > 0) & (df['Close'] < df['Low'].rolling(5).min().shift(1))] = 0
        sig10[(sig10 < 0) & (df['Close'] > df['High'].rolling(5).max().shift(1))] = 0
        sig10[sig10 < 0] *= np.clip(1 - vol_ratio, 0, 1)[sig10 < 0]
        self.signals['S10_HurstSlope_Trail'] = sig10


class VolatilitySignals(BaseSignalFamily):
    def generate_signals(self):
        gld = self.df
        vix = self.vix
        vvix = self.vvix

        if vix is None or vvix is None:
            return

        df = pd.DataFrame({
            'GLD_Close': gld['Close'], 'VIX_Close': vix['Close'], 'VVIX_Close': vvix['Close']
        }).dropna()

        df['GLD_Ret'] = df['GLD_Close'].pct_change()
        df['VIX_Ret'] = df['VIX_Close'].pct_change()

        sig1_base = ((df['GLD_Ret'] < -0.005) & (df['VIX_Ret'] < -0.02)).astype(float)
        self.signals['Base1_DipBuy_V22_Delay1'] = sig1_base.shift(1).clip(-1, 1)

        gld_ma50 = df['GLD_Close'].rolling(50).mean()
        vvix_std20 = df['VVIX_Close'].rolling(20).std()
        vvix_std200 = df['VVIX_Close'].rolling(200).std()
        vvix_10th_pctile = vvix_std200.rolling(200).quantile(0.1)
        sig5_base = (vvix_std20 < vvix_10th_pctile).astype(float) * np.sign(df['GLD_Close'] - gld_ma50)
        self.signals['Base5_Vol_Compression_V9_GLD_Bull'] = sig5_base * (df['GLD_Close'] > gld_ma50).astype(float)

        vrp = df['VIX_Close'] - (df['GLD_Ret'].rolling(20).std() * np.sqrt(252) * 100)
        sig7_base = np.sign(vrp - vrp.rolling(50).mean()) * np.sign(df['GLD_Close'] - gld_ma50)
        self.signals['Base7_VRP_Trend_V23_LongOnly'] = pd.Series(np.where(sig7_base > 0, sig7_base, 0), index=df.index)


# ==============================================================================
# 5. GLOBAL EXECUTION ENGINE
# ==============================================================================
if __name__ == "__main__":
    # 1. Initialize Loader
    loader = DataLoader()
    data_dict = loader.load_data()

    # 2. Automatically discover and instantiate all family classes
    family_classes = sorted(BaseSignalFamily.__subclasses__(), key=lambda cls: cls.__name__)
    families = [family_cls(data_dict) for family_cls in family_classes]

    print("\n" + "=" * 55)
    print("STARTING DYNAMIC ROBUST SIGNAL ENGINE")
    print("=" * 55)

    total_signals = 0
    all_results = []
    summary = {}

    for family in families:
        count, results = family.run()
        summary[family.family_name] = count
        total_signals += count
        all_results.extend(results)
        print(f"  [+] Executed {count} final robust signals for {family.family_name}")
        print(f"  [+] Cumulative signals across families so far: {total_signals}")

print("\n" + "=" * 90)
print("SHARPE RATIOS BY SIGNAL".center(90))
print("=" * 90)
print(f"In-sample period:     {TRAIN_START} to {TRAIN_END}")
print(f"Out-of-sample period: {TEST_START} to {TEST_END}")
print("=" * 90)

for family in families:
    if len(family.results) == 0:
        continue

    print(f"\n{family.family_name}")
    print("-" * 90)
    print(f"{'Signal':<58} {'IS Sharpe':>14} {'OOS Sharpe':>14}")
    print("-" * 90)

    for res in family.results:
        signal_name = str(res["Signal"])[:58]
        print(f"{signal_name:<58} {res['Train Sharpe']:>14.3f} {res['Test Sharpe']:>14.3f}")

    print("-" * 90)